### ISSUE TITLE
[Medium] App Icon & App Title

### ISSUE THREAD

**Issue by benwaffle** [PlayOnLinux/POL-POM-5#107]
![icon](https://cloud.githubusercontent.com/assets/1713819/8150650/ba541bcc-12bf-11e5-87f0-1c77794c718f.png)

**Comment by qparis** [comment]
It is just a Maven setting that need to be set.
If someone wants to do it, feel free

**Comment by Tutul-** [comment]
actually, I correct the icon. I willl try to correct the name too (not a maven setting I think)

**Comment by plata** [comment]
@qparis I think this is fixed. At least my KDE shows "PlayOnLinux" when hovering it in the window list.

**Comment by qparis** [comment]
All right
Anayway, the code is now very different from what it was
