### ISSUE TITLE
Investigate if it is a good ide to implement additional UIs like QTJambi

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#16]
Three questions here:
- Is it worth it?
- What are the the technical blockers?
- What would be the required effort

**Comment by seijikun** [comment]
Even if i love Qt:
I don't think we should nullify the only advantage Java has to give (a UI which can actually be used cross-platform without extra dependencies), while introducing more work to the developers. Since - at least IMO - there would be better languages for that.

**Comment by Veske** [comment]
This could lead to a maintenance nightmare. 
You can go with using JavaFX and have it integrate with host systems very well. For instance see Jetbrains IntelliJ. It is done in Swing but it's the same deal basically. Have not had problems with using it on either Unity, Gnome or i3.

**Comment by qparis** [comment]
Yes I kind agree with that point of view

**Comment by Veske** [comment]
Not sure about that. I have not actually seen a proper JavaFX application on Linux. But judging from what the Jetbrains team has made with Swing I belive it is possible to achieve this on the POL project also.

**Comment by qparis** [comment]
I believe that we could also create a steam-like interface with a strong identity. In that case we would not need to try to immitate system interface

**Comment by Veske** [comment]
Also an idea. Then it would be essential tough that the user can theme the POL client if they wish so. Other than that, I would see no problem with it.

**Comment by qparis** [comment]
We could provide several CSS sets

**Comment by Veske** [comment]
That could work. A bit offtopic here but do you guys happen to have a IRC channel or some place also where it would be possible to chat about the project in real time when needed?

**Comment by qparis** [comment]
#playonlinux-staff on freenode :) Don't be afraid if you see us speaking French. Just say "hum" and we will stop haha

**Comment by Veske** [comment]
Thank you :) Will try to check it out soon and see if I can help this project out also.

**Comment by qparis** [comment]
Many thanks, it is really appreciated

**Comment by qparis** [comment]
gtk-gnome will be used at the end
