### ISSUE TITLE
[Feature Request] Made the Setup Process more clear

### ISSUE THREAD

**Issue by Mannshoch** [PlayOnLinux/POL-POM-5#168]
I made a Mock-up in the hope it could give you some inspiration.

The main goal of this Feature Request is to run the time consuming download and setup process as early as possible and do some other settings while it is working.

![basic](https://cloud.githubusercontent.com/assets/7795891/8878882/fd09d46a-322d-11e5-87f9-50f74cfef88c.png)

![enhance](https://cloud.githubusercontent.com/assets/7795891/8878887/028ad18c-322e-11e5-90a5-4e040804b283.png)

**Comment by qparis** [comment]
Is it for manual installation?

**Comment by Mannshoch** [comment]
Yes, this could made the manual Installation process a bit handier
