### ISSUE TITLE
[Medium] Implement SetupWizard.licence and POL_SetupWindow_licence

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#18]
This step is currently nor implemented in Python (SetupWizard.licence), neither in bash (POL_SetupWindow_licence).
The idea is to look at how SetupWizard.textbox works and do the same for SetupWizard.licence

POL_SetupWindow_licence takes three arguments: 

```bash
POL_SetupWindow_licence "Text" "Title" "File to show"
```
For more details, you can see what POL_SetupWindow_licence is doing in exactly POL_v4 

In POL_v5, the Title is always attached to SetupWizard and not to a given step. Therefore, the Title argument in bash will be a stub put for backward compatibility

**Comment by Tutul-** [comment]
working on it

**Comment by Tutul-** [comment]
it's ok now, no ?

**Comment by qparis** [comment]
Yes! Thank you
