### ISSUE TITLE
[Easy] Implement missing Bash POL_SetupWindow_presentation and POL_SetupWindow_free_presentation

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#2]
Currently, POL_SetupWindow_free_presentation and POL_SetupWindow_presentation (Look at com.playonlinux.framework.SetupWizard.java) are not implemented in bash:

To achieve that, we need to: 
* Add to bash/setupWindow the unsupported keywords
* Add them to python/SetupWindow/SetupWindowNetcatCommandParser.py 

Implementing these steps will ensure backward compatibility with POLv4

**Comment by Tutul-** [comment]
Done, you can check at https://github.com/PlayOnLinux/POL-POM-5/pull/78
