### ISSUE TITLE
[Feature Request] Ad an Update Option for Scripts

### ISSUE THREAD

**Issue by Mannshoch** [PlayOnLinux/POL-POM-5#216]
If a Program works better on a new Wine Version it should be allowed to update a Prefix.

In the easiest way POL user detect that a Wine Upgrade to a specific Version result in a better Performance, it should be posible to update a Prefix with that.

It could show like follow, IMHO:
To get a Prefix update, the follow situation have to be. Now manual change where made on a Prefix with POL. Maybe an Expert Override Option can reactivate the Update. So a Program installed from a POL-Script should deactivate all manual Option on that Prefix and allow to activate them if you tick an override Option.

POL Scripts should be able to contain an Upgrade section.

If an Upgrade is available you get noticed after start POL and you are able tu Update with one click. (Maybe with a backup option)

**Comment by Tutul-** [comment]
Maybe, by default, check for modification and propose update (with checkbox for backup ?). Many user prefer automatic process. So the update check can be by default "on" and propose (by prefix) : backup (checkbox), ignore this update, never update (and never check ? can be manage in configuration of the prefix) and update. But the process can also retard the launch of POL (more process to do on startup). We must find a efficient way to do that :) but good idea ^^

**Comment by FuzzyToothpaste** [comment]
This should not be just for changes to the recommended Wine version, but for any changes at all that should be made to the program (like installing a new library). I think we should do this in a revision-type format. When someone releases an update to a script, they should make the one used for installing the program like usual and make a much smaller script for upgrading from 1.0 to 1.1. We can let people make short scripts to make the little tweaks that would improve the program. If someone has 1.0 installed, did not update to 1.1, and now 1.2 is current, PlayOnLinux should upgrade them to 1.1 first and then 1.2. I think that is easily the best way to implement something like this.

**Comment by Tutul-** [comment]
Not a good idea. If someone will install the game and it've already 5 or 7 patch, the user must wait 6 or 8 installation and upgrade ? No sens !
But, with the script structure, we can now, for an upgrade, check the difference between my "installed version" and the "updated version" of the script and applied them. Easier for new installation and, with the current script structure, can be very effective.

But variable think like wine version, library requirement and configuration of wine must be very structured in the script for that. Maybe variable (liste for library ?).
