### ISSUE TITLE
Consider creating a gitter channel for the repo

### ISSUE THREAD

**Issue by seijikun** [PlayOnLinux/POL-POM-5#22]
I've seen gitter multiple times on other repos.
I don't know how it works or how it's set up, but if it is easy - it would be cool to have one for easier communication.
The only info-page i could find is [here](http://blog.gitter.im/about/).

**Comment by qparis** [comment]
What are the advantage of gitter compared to IRC?

**Comment by seijikun** [comment]
It's directly on GitHub and you don't need an IRC client.
But I'm totally fine with IRC (I didn't know there is one).
