### ISSUE TITLE
[Medium] Add filter feature in InstallWindow 

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#24]
Three filter checkbox have been added to the installation window. We now need to connect these three checkboxes to the domain object. 
In order to do that, we need to:
* Add the following two methods in the com.playonlinux.ui.api.RemoteAvailableInstallers interface 
** Iterable<ScriptDTO> getAllScripts(String filter, boolean commercial, boolean requiresNoCd, boolean testing);
** Iterable<ScriptDTO> getAllScriptsInCategory(String categoryName, boolean commercial, boolean requiresNoCd, boolean testing) throws PlayOnLinuxError;

* The original methods should call these new method with the default behavior (true, false, false) 
* Implement the two methods in RemoteAvailableInstallersPlayOnLinuxImplementation
* Use these new methods in AvailableInstallerListWidget

The design of this feature can be improved later to allow to add extra filters.

**Comment by seijikun** [comment]
I am currently working with this code anyway, so I'll take this one.

**Comment by seijikun** [comment]
Is it intended, that `ScriptInformationsDTO` does not contain the commercial flag?

**Comment by qparis** [comment]
isCommercial = !isFree in fact. 
It is the way the information is stored in the database.

**Comment by seijikun** [comment]
This has been implemented by #91.

**Comment by qparis** [comment]
We still need to implement the behavior of the filter, but it should be easy. The big part of the work has been done :)
