### ISSUE TITLE
[Medium / Difficult] Find suitable libraries to extract archives. 

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#25]
We need to find one or several libraries to be able to extract the following archives (by order of priority)
- cab
- zip
- tar.gz / tar.bz2
- 7z
- rar

The library should be a Maven dependency if possible

**Comment by seijikun** [comment]
Probably the best one would be [this one](https://commons.apache.org/proper/commons-compress/) here. It has support for ar, cpio, Unix dump, tar, zip, gzip, XZ, Pack200, bzip2, 7z, arj, lzma, snappy, DEFLATE and Z files.

I don't know about rar. Isn't rar licenced in some way?

**Comment by qparis** [comment]
For the main part, it seems to be what we need. We still need something for .cab files though

**Comment by Tutul-** [comment]
maybe this can be use ?! (not tested) http://sourceforge.net/projects/cablib/

**Comment by qparis** [comment]
This one does not use for cab.

**Comment by madoar** [comment]
I may have found a suitable library to extract .cab files, see [here](https://github.com/dorkbox/CabParser).
The library seems to be undocumented, but at least someone asked for a short example in an issue, which the author provided, see [here](https://github.com/dorkbox/CabParser/issues/2).

**Comment by plata** [comment]
Shall we split this into:
* extract archives with Apache Commons Compress
* extract .cab with CAB PARSER

Just to have tasks someone can start working on.

**Comment by qparis** [comment]
We shall split this ticket. The main work is already done, but we still need something to extract .cab files ideally

**Comment by qparis** [comment]
Also we will need to extract icons from PE files

**Comment by plata** [comment]
Split to #742, #743, #744.
