### ISSUE TITLE
[Advanced] Find a more lightweight alternative than Spring for the Rest Service 

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#26]
Currently, we are using Spring framework for REST requests. 
However, this piece of library takes 15Mo of diskspace. It could be good to find an alternative, and save save some space.

**Comment by seijikun** [comment]
How about [Jersey](https://jersey.java.net/), a reference implementation of [JAX-RS](http://jax-rs-spec.java.net/)?
However, I am not sure how the licens(es) of Jersey work with the GPLv3.

**Comment by qparis** [comment]
Jersey seems to be also distributed in GPLv2.
You remind me that we need to check all the other dependencies though

**Comment by yawkat** [comment]
Why do all dependencies have to be GPL? I thought GPL only forced the other way around?

**Comment by qparis** [comment]
In fact, not GPL but but there are some incompatibilities. (Because other licences may also have restrictions)

**Comment by yawkat** [comment]
Ah okay, so you can work with apache and mit and such? I think there's a maven plugin to actually detect incompatibilities there

**Comment by qparis** [comment]
Yes I guess that should work :) If you find how to setup this plugin, it can be interesting

**Comment by yawkat** [comment]
Okay I will take a look when I'm home, thanks for answering.

**Comment by yawkat** [comment]
Well, apparently the plugin I was thinking of only has blacklisting, not whitelisting. You can however use `mvn net.surguy:maven-displaylicense-plugin:0.6:displaylicense` to list all licenses of all dependencies. Sadly jersey itself doesn't have them included but it looks like jersey and glassfish are GPL and two other dependencies are apache.

**Comment by qparis** [comment]
Sounds good. 
For the rest API, I think we can stick with our own download class + Jackson to decode json.
It will allow us to factor download task that are not always RESTful (scripts & resources download) with the REST service.
