### ISSUE TITLE
[Suggestion] Use lombok

### ISSUE THREAD

**Issue by Tomahna** [PlayOnLinux/POL-POM-5#262]
https://projectlombok.org/

Using Lombok would be a good idea to reduce the amount boilerplate code.

**Comment by Veske** [comment]
Looks like too much magic in my opinion.

**Comment by Tomahna** [comment]
I kinda doubt that the high verbosity of Java was the reason of this choice. I guess it was because it's cross platform, typed and well spread.

Reducing the amount of code like this usually improve it's readability and overall quality. But i guess it can disturb unused devs.

Anyway it's not a choice for me to make, that's just a suggestion. You can close this issue if you consider it's not adapted to your project.

**Comment by qparis** [comment]
Could it be easily integrated to maven? 
I think we should think about dividing PlayOnLinux into submodules

**Comment by Veske** [comment]
Do you want to use maven module system for it or wait for Jigsaw project?

**Comment by qparis** [comment]
I guess we can use maven for the moment

**Comment by Tomahna** [comment]
That would definitely help a lot for code comprehension and unit testing.
