### ISSUE TITLE
[Suggestion] Replace log4j by slf4j + another logging tool

### ISSUE THREAD

**Issue by Tomahna** [PlayOnLinux/POL-POM-5#263]
Log4j is clearly obsolete. Whatever the logging framework you wish to use, log4j references should be replaced by slf4j ones to make it easier to switch.

**Comment by Veske** [comment]
You could assign that task on your self too. I agree, Log4j is deprecated.

**Comment by Tomahna** [comment]
Sure, it wasn't a someone should do it request. I just intended to check if people agree on this before doing it.

**Comment by Veske** [comment]
You could try joining #playonlinux-dev on Freenode to and ask there. But because of the recent news in France they have been quiet right now. I hope everything is okay with the main devs.

**Comment by qparis** [comment]
Agreed. You can go ahead if you want

**Comment by Veske** [comment]
Close the issue?

**Comment by Tomahna** [comment]
Indeed
