### ISSUE TITLE
[Test Failure] FileAnalyserTest testLineSeparatorCRLF

### ISSUE THREAD

**Issue by Tomahna** [PlayOnLinux/POL-POM-5#273]
The unit test FileAnalyserTest.testLineSeparatorCRLF fails with : 
    org.junit.ComparisonFailure: expected:<[
    ]
    > but was:<[]
    >

Seems to find \r instead of \r\n

Problem encountered since the project split. 
Test fails when launched with JUnit, m2e, and standalone maven version.
System is a standard Ubuntu 15.10.

**Comment by qparis** [comment]
Have you tried to reclone the repository from scratch?

**Comment by Tomahna** [comment]
Yes i did.

**Comment by qparis** [comment]
How can we explain that it runs under other circompstances? What is your JDK version?

**Comment by Tomahna** [comment]
Java : openjdk version 1.8.0_66-internal
Maven : 3.3.3

**Comment by Tomahna** [comment]
Tested on my server
Fails with Apache maven 3.0.5, opendjdk 1.8.0_45-internal on ubuntu 15.04

Same problem.

**Comment by qparis** [comment]
In fact Git is enforcing line endings...

**Comment by qparis** [comment]
Should be fixed

**Comment by Tomahna** [comment]
Ok for me.
