### ISSUE TITLE
[Test Failure] WineInstallationTest

### ISSUE THREAD

**Issue by Tomahna** [PlayOnLinux/POL-POM-5#276]
Cannot run program "/home/magnus/Workspaces/PlayOnLinux/playonlinux/phoenicis-wine/target/test-classes/com/playonlinux/wine/bin/wine" (in directory "/tmp"): error=2, Aucun fichier ou dossier de ce type

It seems that the script used to test disappeared during the project division.

(I'll submit a pull request asap)

**Comment by qparis** [comment]
Should be fixed

**Comment by Tomahna** [comment]
Ok for me.
