### ISSUE TITLE
[Feature Request] Integrate an uninstall option into Apt

### ISSUE THREAD

**Issue by Mannshoch** [PlayOnLinux/POL-POM-5#293]
A strange Idea. Could it be maybe possible to Enter applications into Apt-get?

e.g.
![pol-app](https://cloud.githubusercontent.com/assets/7795891/11851542/7875b048-a433-11e5-9a11-b159c25e2c0d.png)
and
![pol-apt](https://cloud.githubusercontent.com/assets/7795891/11851552/7fd1dac4-a433-11e5-9959-3cfce16369b5.png)

**Comment by Veske** [comment]
Is it even possible? These wine applications are locally installed application put into your home directory. I don't think these APT frontends deal with these applications.

**Comment by mulx** [comment]
This won't be possible, apt works only with .deb package and they can only be installed by privileged user (root or sudoers). 
PlayOnLinux use it's own mechanism to install apps in the user home directory without any privileges. 
To make this request possible, PlayOnLinux will have to make .deb package and install it with dpkg with a privileged user (dpkg can handle file anywhere on the system, so even in /home it will work, thought it is really not recommended). 
Also, as we support more system than just Ubuntu/Debian, this will required making a .rpm for Fedora/CentOS/RHEL/…, an .ebuild for Gentoo, an etc (and they have the same restriction).

**Comment by Mannshoch** [comment]
An alternated Idea. But it depends on the file system (btrfs ?). It seems that modern File systems has the ability to create a Layer on that every change in a File system will be placed. For uninstalling a Windows Program you only have to remove this Layer. If you expand this Idea you could differ between Wine Prefix installation, Windows programs and wine tricks installations and remove or replace specific elements easy.

**Comment by mulx** [comment]
I don't see any advantage with what we have now (currently we just have to rm the wineprefix and some shortcuts, this does not depend on file system… )

**Comment by Veske** [comment]
I think you should look at this problem like this:  what you are doing with POL is not normal. You install some programs on your system that are then "emulated" by wine. You definently don't want to give such things any sudo permissions so you have a nice little container in your /home where all these foreign applications are stored.

Now POL client is nice and also allows you to nicely manage these installed applications - letting you remove them completely from your system if so you want.
These application should never be allowed to see the light of sudo access(this is what APT and stuff need).

**Comment by Mannshoch** [comment]
Thanks a lot for your comments. I know these Ideas where strange. But sometimes such strange ideas could give new Input and maybe open new potentials.

I like Wine and what I can do with that but I do no like their software and how to handle it. PlayOnLinux is here far more innovative and End-user friendly. Lets see what we get at the end of this rewriting.

Thanks a lot for all of your work and doing in your spacetime
