### ISSUE TITLE
Change observer / observable pattern

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#294]
Currently, we are using Observer / Observable pattern. 
This pattern makes the code hard to read and generates a lot of type warnings. 

I suggest that we use an event based approach. We could use java.util.function.Consumer<T> and java.util.function.Supplier<T> to allow user interface to be notified. 

Eg. It would look like this: 

 downloader = new Downloader(); 
 downloder.setOnDonwloadHook(progress -> progressBar.setPercentage(progress));

**Comment by qparis** [comment]
This has been done here for the directory watchers as an example: 
https://github.com/PlayOnLinux/POL-POM-5/commit/ec84edc97d0218ddc91057f9f449cfbf76233312

**Comment by Veske** [comment]
Hmm... scope seems big :D What module should go first?

**Comment by qparis** [comment]
The first class will be HTTPDownloader I think. @Tomahna wants to handle it. 
I think we could watch com.playonlinux.apps then

**Comment by qparis** [comment]
HTTPDownloader has been handled here: https://github.com/PlayOnLinux/POL-POM-5/pull/296

**Comment by Tomahna** [comment]
#304 should allow us to close this issue.

**Comment by qparis** [comment]
Issue closed. Good work
