### ISSUE TITLE
Problems compiling POL5 on latest Arch, Gnome 3.20

### ISSUE THREAD

**Issue by sciencefyll** [PlayOnLinux/POL-POM-5#324]
Trying to install the latest git version on Arch.
jdk8-openjdk, maven 3.3.9, java-openjfx are installed.

Heres the error:
`[ERROR] Failed to execute goal on project phoenicis-qt: Could not resolve dependencies for project com.playonlinux:phoenicis-qt:jar:5.0-SNAPSHOT: Could not find artifact com.trolltech:qtjambi:jar:4.8.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

Complete output: http://pastebin.com/w6W7Ca1q

Any idea why this happens?

**Comment by Tomahna** [comment]
Just run mvn clean, it will install qtjambi in your local maven repository. Compilation should work afterward.
