### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Veske** [PlayOnLinux/POL-POM-5#328]
Do we have a roadmap somewhere with features still needed for a first release?

**Comment by Tomahna** [comment]
In my opinion, before adding features, it would be nice to reduce the overall application complexity.
A few steps that might help are : 
- replacing phoenicis-injection by a standard injection framework (spring, guice)
- replacing the custom i18n code by standard java i18n
- replace  custom interfaces by java 8 functional interfaces
- replace anonymous classes by lambdas

Theses steps would help to reduce the application to a more "manageable" size.

**Comment by ruixiangTan** [comment]
great software, cannot wait for it's debut!
