### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#331]
I'm wondering how the development of Play on Linux 5 is progressing. 
The last news post about Play on Linux 5 I've found is from September 2015, which is now over one year old. 
How is the current state of Play on Linux 5? What needs to be done and what is already finished? Can you estimate a release date or a roadmap that tells us the current milestones? 
I'm one of the users that would like to use Play on Linux 5 as soon as possible, so in addition to the previously stated questions I would also like to know if there is a plan to adapt the bash scripts for Play on Linux 4 to work with Play on Linux 5, or to write new ones for Play on Linux 5.

**Comment by seijikun** [comment]
I think the [contribution graph](https://github.com/PlayOnLinux/POL-POM-5/graphs/contributors) is representing the current progress quite nicely.
I'm currently fully occupied by other things, so I've got no time to work on this project. This will, unfortunately, probably also stay this way for quite some time still.

Regarding the scripts:
POM5 will support the old scripts but also defines a new script format.
I, however, do not know if it will stay this way, or if the support for the old ones is removed. This would require the old ones to be ported, which is a huge task for people that do this in their freetime.

**Comment by qparis** [comment]
Hi,
I'm currently thinking about simplifying a lot the project. The new idea we had recently is to store all the scripts on a git repository. Since most of the script are now outdated, I think it would be preferable to start from scratch.

Stay tuned.
