### ISSUE TITLE
[Easy] Implement TeeApplicationsSource

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#332]
This will allow PlayOnLinux to use third parties repositories for scripts. 

Please comment for further details

**Comment by samrocketman** [comment]
The subject and description aren't clear to me.

**Comment by qparis** [comment]
Ok, then

ApplicationSource is an interface that provides to PlayOnLinux a list of application source.

We already have two implementations of this interface: GitApplicationSource (that will download scripts on a git repository) and LocalApplicationSource (that will fetch the scripts on a Local Directory)

We need a TeeApplicationSource that will take as Input two instances of ApplicationSource and will fetch the scripts for both of them. 

* This component will need to merge the categories and the application properly. 
* If two scripts with the same name are found, we need to take the first one

**Comment by plata** [comment]
I think it would be better to take the local one instead of the first one. That way, you could easily update a script and try it.

**Comment by qparis** [comment]
What do you mean? PoL should be able to handle bot of them, this is the idea of this ticket

**Comment by plata** [comment]
Yes. My comment was a reply to

> If two scripts with the same name are found, we need to take the first one

So my idea was to always use the local script if two scripts with the same name are found. Of course, this would require to know which side of the tee is local.

**Comment by qparis** [comment]
No the idea is to take the first one always, and the order set in the configuration will matter

**Comment by qparis** [comment]
And also, the local version should not be proprietary, because if so, we won't be able to push script updates

**Comment by qparis** [comment]
prioritary *

**Comment by qparis** [comment]
Oh I haven seen while reviewing, but you can't put a Map in the DTO. It is not json serializable

**Comment by samrocketman** [comment]
> And also, the local version should not be proprietary, because if so, we won't be able to push script updates

Most software that I've used which allows things like this prioritizes local.  If a user has a local set of scripts (i.e. development or customizations) they _don't expect_ anything else to override their customized scripts.

> No the idea is to take the first one always, and the order set in the configuration will matter

If the set order is configurable by the user then I'd be fine with that behavior as well rather than always prioritizing local.

**Comment by qparis** [comment]
You should make a difference between userside things and applicationside things. 
Concerning the script, the priority would be User > Internet > Application

**Comment by plata** [comment]
> you can't put a Map in the DTO. It is not json serializable

Is it ever serialized? As far as I can see, only category name and type are read from the .json.
Otherwise: what solution would you prefer?

**Comment by qparis** [comment]
The json could be directly read from a webservice (in was the original implementation in fact), or we could imagine asking ApplicationSource to serve a webservice for another POL instance later. 
I'll commit a Pull request to show you what I have in my head. In general, it is a bad practice to put variable data in keys.
