### ISSUE TITLE
Arch Linux - cannot start application

### ISSUE THREAD

**Issue by mdeguzis** [PlayOnLinux/POL-POM-5#334]
Works but cannot install applications:
```
java -classpath "$CLASSPATH" com.playonlinux.app.PlayOnLinuxApp "$@"
```

Does not work:

```
java -classpath "$CLASSPATH" com.playonlinux.javafx.JavaFXApplication "$@"
```

Error: https://gist.github.com/mdeguzis/f1b60895a158c48dc438151200fd1514

What is the correct classpath? I am trying to fix up the AUR package:

https://aur.archlinux.org/packages/playonlinux5-git

I did try setting "export JAVA_HOME="/usr/lib/jvm/java-8-openjdk" after removing openjfx and then installed openjfx again, per [build notes](http://wiki.playonlinux.com/index.php/Building_PlayOnLinux_5).

I did do some tests and set my current java to openjdk-8 and used the below script to test:

```
#!/bin/bash

POL_HOME=/opt/playonlinux5
CLASSPATH=${CLASSPATH}:$POL_HOME/lib/*

java -classpath "$CLASSPATH" com.playonlinux.javafx.JavaFXApplication "$@"
```

**Comment by qparis** [comment]
It appears that you have an package ; the classes in the stacktrace do no longer exist

**Comment by mdeguzis** [comment]
`an package;` ? Perhaps the dist zip is missing components? If the wiki is old, I can help update it.

**Comment by qparis** [comment]
outdated * sorry

**Comment by mdeguzis** [comment]
Thanks was on a new build. I'll axe the clone of the repo I have and do a fresh build.

**Comment by mdeguzis** [comment]
phoenicsis-dist.zip only contains the script, no libs. Are build instructions now different? This was after `mvn clean build`

**Comment by qparis** [comment]
I'm not sure but the class EventHandlerLibrary does no longer exist. Can you investigate why do you have it on your stacktrace?

**Comment by mdeguzis** [comment]
That must have been left behind from a dirty pkg/ dir. I'll look more at the new build log. Previously, unzipping the archive could rained all that was required.

**Comment by mdeguzis** [comment]
Build log for AUR package: http://slexy.org/view/s20CCK5rGS

**Comment by qparis** [comment]
I think it was because of this: https://github.com/PlayOnLinux/POL-POM-5/pull/340

phoenicis-app do longer exist, therefore, it was not cleaned when you run mvn clean. 

Can you retry please? :)

**Comment by mdeguzis** [comment]
The tree is populated, but it will not launch: http://slexy.org/view/s21QrvuzkQ , so closer :P

**Comment by qparis** [comment]
Can you check that com.playonlinux.javafx.JavaFXApplication is on your classpath?

**Comment by mdeguzis** [comment]
Last bit was my fault. I forgot to re-add the POL home path in the script for the AUR package. All good! Thank you for clearing things up.
