### ISSUE TITLE
Assembly is empty

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#335]
```
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'com.playonlinux:phoenicis-app'
```

Shouldn't it be com.playonlinux:phoenicis-apps?

**Comment by qparis** [comment]
It should be phoenicis-javafx and/or phoenicis-cli depending on what you want to run

**Comment by plata** [comment]
I have tried phoenicis-javafx. However this is giving me:

[error output](https://github.com/PlayOnLinux/POL-POM-5/files/673203/error.output.txt)

**Comment by qparis** [comment]
Seems like a property is missing on Linux.properties

nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.user.wineprefix' in string value "${application.user.wineprefix}"

**Comment by plata** [comment]
That fixed it. I will do a pull request.
