### ISSUE TITLE
Use standard maven directory layout

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#336]
Use the standard maven directory layout such that anyone familiar with maven can quickly understand the source code structure of PoL. This should make contribution easier.

**Comment by qparis** [comment]
They are totally standard AFAIK

**Comment by plata** [comment]
Was thinking of this: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by Veske** [comment]
https://github.com/PlayOnLinux/POL-POM-5/tree/master/phoenicis-dist/src/assembly

Notice the /src/assembly.

phoenicis-dist is just a maven module that helps keep dependencies separate.

**Comment by plata** [comment]
I see. So instead of having assembly for javafx and cli there is only one for PoL which is located in a separate module.

Btw: What's the meaning of phoenicis?

**Comment by qparis** [comment]
It is just a code name :)

I think we can close this ticket
