### ISSUE TITLE
Selecting a theme has no effect

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#346]
I can select a theme in JavaFX → Settings. However, the look does not change.

**Comment by qparis** [comment]
Yes, this is broken for now. It needs to be implemented differently

**Comment by plata** [comment]
If you could provide some hints, how it should be done, I might look into it.

**Comment by qparis** [comment]
I guess a first good step would be to pass the CSS to be loaded as a property. For that, we could use the @Value notation

**Comment by qparis** [comment]
The CSS is loaded on PlayOnLinuxScene class, which is instantiated in MainWindow
MainWindow is instantiated by MainController which is a Spring bean. Therefore, the property could be loaded in MainController and injected to the right place via the constructorss

**Comment by plata** [comment]
The theme should be user specific. Therefore I think we need a user specific config file for this rather than using OS.properties. This could be done with Java preferences API (maybe in combination with Spring's PreferencesPlaceholderConfigurer).

**Comment by qparis** [comment]
We need to handle the user specificeness separately, because all properties are concerned by this

**Comment by plata** [comment]
Yes. So the settings should be saved in the OS.properties for now?

**Comment by qparis** [comment]
The default skin will be saved here yes

**Comment by qparis** [comment]
Duplicates with #365
