### ISSUE TITLE
Mark selected category in "Apps"

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#370]

**Comment by qparis** [comment]
I am not sure that it will really bring something, moreover there are not always a concept of "selected category"

**Comment by plata** [comment]
How can you access an application which does not belong to a category?

**Comment by qparis** [comment]
Every app has a category, but you can display apps from multiple category. (e.g. if you use the search bar)

**Comment by plata** [comment]
Ok. In this case, you're right that marking the category doesn't make sense. 

Nevertheless, I'm not sure if it's good to place the categories in the sidebar then. Feels a bit mixed from the design concept.
