### ISSUE TITLE
Setup unit test infrastructure for phoenicis-apps

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#373]

**Comment by qparis** [comment]
We do not need to write ticket for test infrastructure. When you need to have unit test for a package, just add the two Maven dependencies and you are good to go

**Comment by qparis** [comment]
No need to add these dependencies until the test framework is not used, exactly as any other dependency

**Comment by plata** [comment]
What about folders, mocks etc? Might be duplicate work if multiple people start writing unit tests at the same time. Also it's easier to get started if you never did a unit test with Maven/Java/Spring (like me).

**Comment by qparis** [comment]
The dependencies are set in dependenciesManagement / properties in the root project. The folders should automatically be created by your IDE when you write the test.
See multithreading package for an example
