### ISSUE TITLE
[Easy] Write unittest for TeeApplicationsSource

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#386]
See: Implement TeeApplicationsSource #332

The test shall show that:

- categories which occur in only one of the two ApplicationSource occur also in the merged result
- if an application occurs in both ApplicationSource, the one from the rightApplicationSource
- merged applications should contain resources, scripts and miniatures from both ApplicationSource

**Comment by plata** [comment]
@qparis can this be closed?

**Comment by qparis** [comment]
So far yes
