### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#392]

**Comment by plata** [comment]
Please provide a more detailed description of what has to be done here.

**Comment by plata** [comment]
Here is a [tutorial](https://docs.oracle.com/javase/tutorial/i18n/index.html). We could use this with [Transifex](https://docs.transifex.com/formats/java-properties).

**Comment by plata** [comment]
There are several issues open regarding localization (this, #4, PlayOnLinux/Scripts#49). Can we agree how we want to do localization and define a roadmap of what has to be done to achieve this? I would then like to create the required tasks for this such that people can start working on it.

**Comment by plata** [comment]
Superseded by #808.
