### ISSUE TITLE
Install opens tab in "Library"

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#393]
Clicking "Install" opens a new tab in "Library" but does not switch to this tab. Either switch to this tab or use a pop-up window.

**Comment by qparis** [comment]
This is a regression because it worked before

**Comment by Brainzyy** [comment]
This was fixed as far as I can see. @qparis @plata

**Comment by qparis** [comment]
Yes, it is fixed :-)

**Comment by Brainzyy** [comment]
@qparis Just wanted to let you know, so this one can be closed :)

**Comment by qparis** [comment]
Thanks :)
