### ISSUE TITLE
Cannot close PoL JavaFX after running an application

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#395]

**Comment by qparis** [comment]
You should be able to but the application needs to be closed

**Comment by plata** [comment]
I see. That's confusing with Steam games because Steam is not closed when you close the game.

**Comment by qparis** [comment]
I agree but we have no really other choice.
The other way is to do as we did with POL 4 : kill all prefixes when POL is closed

**Comment by plata** [comment]
Could we list the running applications and ask if they shall be killed?

**Comment by qparis** [comment]
You can look at what wineserver binary proposes. I know that for a given prefix, you can wait for wine to be closed or you can kill all the processes. I don't know if you can list the prefixes that are used.

The other way would be to handle something in the shortcut, but the design needs to be well thought 

Maybe

**Comment by plata** [comment]
We should at least show a hint that PoL cannot be closed because wine is still running.

**Comment by qparis** [comment]
The process can't, but the windows can

**Comment by plata** [comment]
see #448
