### ISSUE TITLE
Wine Gecko & Mono

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#396]

**Comment by plata** [comment]
Please provide more information about what has to be done.

**Comment by qparis** [comment]
Each wine version has a link to a gecko and a mono bundle (see http://phoenicis.playonlinux.com/index.php/wine?os=darwin). 
When installing a wine version, the corresponding bundle of gecko should be downloaded once in a resources/gecko directory. Then, a symbolic link should be made from this directory to {{ WINE_VERSION }}/share/wine/gecko/. 

Same rules applies for Mono
