### ISSUE TITLE
Shortcut: Steam.exe -applaunch not working

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#401]
Using `-applaunch` instead of `steam://rungameid/` is not working (Steam opens, but does not start the game).

To reproduce: install "Dr. Langeskov, The Tiger, and The Terribly Cursed Emerald: A Whirlwind Heist"

**Comment by qparis** [comment]
I don't understand, I have tested with Black Mesa yesterday

**Comment by plata** [comment]
Strange. Maybe it's only in combination with certain characters in the prefix name?

**Comment by qparis** [comment]
What about the other scripts like Hexcells?

**Comment by plata** [comment]
Doesn't work for me. 

Changed from:
```
"arguments":"steam://rungameid/265890"
```

to:
```
"arguments":"-applaunch 265890"
```

**Comment by qparis** [comment]
Try to pass an array: ["-applaunch", 265890]

**Comment by plata** [comment]
Yes that works. But can we expect that people write their scripts like this?

**Comment by qparis** [comment]
Sure :-) It's much easier that having to think about which space needs to be escaped

**Comment by plata** [comment]
Ok.

**Comment by qparis** [comment]
The other option would be to use a command line parser, but it is not obvious at all to test all the corner cases
