### ISSUE TITLE
SetupWizard: implement file selection page

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#422]
Should have a standard text ("Please select the installation file for $app_name.") to keep translation simple and an additional hint text which can be filled with custom information.

**Comment by qparis** [comment]
For the record, we currently have this: 
<img width="1022" alt="capture d ecran 2017-01-05 a 21 50 50" src="https://cloud.githubusercontent.com/assets/373645/21697084/083d749e-d391-11e6-90eb-7f8085fb5b64.png">

**Comment by plata** [comment]
Ok. Did not see that one. I looked at phoenicis-scripts because the SetupWizard is located there. Can we have a wiki page in [Scripts](https://github.com/PlayOnLinux/Scripts) describing the available steps?

**Comment by plata** [comment]
Nevertheless I think we should have this division in standard text and custom text to reduce the translations.

**Comment by plata** [comment]
The translations could also be reduced by [Scripts issue 92](https://github.com/PlayOnLinux/Scripts/issues/92).
