### ISSUE TITLE
Long game titles get shown incorrectly

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#431]
![Screenshot 1](https://cloud.githubusercontent.com/assets/8126341/21729971/d8da651e-d44d-11e6-9534-94886e2e6882.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/8126341/21729976/de9bf490-d44d-11e6-878d-c4427dcd48bd.png)

**Comment by qparis** [comment]
Yes this is made so that the space between the pictures remain the same. Otherwise it does not look good

**Comment by Brainzyy** [comment]
@qparis Ah, I see. The only thing that could be changed is that it doesn't show the top part of the next line, because IMO it's a little messy.

**Comment by plata** [comment]
Usually, it should just cut off the text if it is too long.

I think we should add "..." if the text has been cut and show the full title on hover.

**Comment by Brainzyy** [comment]
@plata That's exactly what I was trying to say :)

**Comment by qparis** [comment]
Agreed

**Comment by plata** [comment]
@Brainzyy are the pictures from "My applications"? In "Apps" it should be ok.

**Comment by Brainzyy** [comment]
@plata They are from "Apps", clicked on the category "Games"

**Comment by Brainzyy** [comment]
@plata if you maximize the PlayOnLinux screen, do the Games scale to take up the whole screen? because on my end, they don't.

**Comment by plata** [comment]
@Brainzyy they do not scale.

**Comment by Brainzyy** [comment]
@plata I just checked on my iMac and the issue is not present there. On my iMac I get the same result as in your screenshot. It must be a driver or gfx card difference/issue then.

**Comment by plata** [comment]
Do you have different screen resolutions? The `MiniatureListWidget` uses `setWrappingWidth()`. Maybe this should be bind like [here](https://stackoverflow.com/questions/40631744/how-to-make-javafx-text-wrap-work).

**Comment by Brainzyy** [comment]
@plata The computer that works like it should (like your screenshot) has a 1920x1080 res screen and the system that the screenshot of the OP is from has a 1440x900 res.

**Comment by plata** [comment]
I guess it's related to the `clip()` then. Should be fixed by #435.

**Comment by Brainzyy** [comment]
@plata Fixed indeed. Thank you!
