### ISSUE TITLE
Question to remove container after removing app is not shown correctly

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#432]
![Screenshot](https://cloud.githubusercontent.com/assets/8126341/21729944/a7f663b2-d44d-11e6-8bea-cb2c6c35a365.png)

**Comment by plata** [comment]
You can directly embed the picture on GitHub. Just drag and drop it here.

**Comment by Brainzyy** [comment]
@plata Thanks, fixed that.

**Comment by plata** [comment]
The problem must be in `JavaFXSetupWindowUIConfiguration`.

**Comment by plata** [comment]
@Brainzyy should be fixed now. Please check and close if so.

**Comment by Brainzyy** [comment]
@plata Confirmed fixed, thanks.
