### ISSUE TITLE
JavaFx: SetupWizard doesn't scale

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#434]

**Comment by qparis** [comment]
This will be very hard to scale it because of the left image

**Comment by plata** [comment]
Do we really need the left image? It doesn't add any value in my opinion.

**Comment by qparis** [comment]
Yes I think we do. It allows the customize the scripts, and we have a lot of already made left images/

Also, if you remove it, the presentation screen will feel very empty

**Comment by plata** [comment]
To be honest, creating the left image to me always was one of the most annoying things with PoL 4. Moreover, I believe that not using custom left images would make installing applications feel more like a PoL install rather than PoL calling some script.

I agree with the empty feeling though. But if we use the current playonlinux image all the time, we could replace the image by some JavaFX Text.

**Comment by qparis** [comment]
All right, I agree on that
