### ISSUE TITLE
[Suggestion] Add an option to specify where PlayOnLinux is installed

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#436]
Would this be possible? 
This could be useful to test #427 further.

**Comment by qparis** [comment]
This is a configurable property :-)

**Comment by Brainzyy** [comment]
@qparis How would I go about doing this? :)

**Comment by plata** [comment]
@Brainzyy it's the `application.user.root` property. You can set it in phoenicis-configuration/resources/Os.properties.

**Comment by Brainzyy** [comment]
@plata Thanks that worked.
