### ISSUE TITLE
Wrong wineserver started

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#463]
I get:
```
wine: '/home/plata/.PlayOnLinux-5/wineprefix//Mirror's Edge™' is a 64-bit installation, it cannot be used with a 32-bit wineserver.
```

When I run from command line, it works:
```
env WINEPREFIX="/home/plata/.PlayOnLinux-5/wineprefix/Mirror's Edge™/" wine Steam.exe --applaunch 17410
```

**Comment by qparis** [comment]
You seems to have created a prefix with a 64bits wine and changed the architecture afterwards. The architecture of a prefix should not be changed

**Comment by plata** [comment]
I don't think I did that. I have this error with several prefixes.

**Comment by qparis** [comment]
We changed the default architecture to 32bits recently. Could it explain this?

**Comment by plata** [comment]
Maybe. But how could this affect existing prefixes?

**Comment by qparis** [comment]
It should not. Can you check PlayOnLinux.cfg

**Comment by plata** [comment]
It says:
```
"wineArchitecture":"x86"
```

**Comment by qparis** [comment]
It should not. The behavior of wine is not correct then. 
The default architecture should be 32bits only if it is not set in the configuration file (same for the distribution)

**Comment by plata** [comment]
I think I found it.

**Comment by Brainzyy** [comment]
I could be completely stupid here, but could this be related to #427 in any way?

**Comment by plata** [comment]
@Brainzyy I was thinking so as well. Just try again after PlayOnLinux/Scripts#114 is merged.

**Comment by Brainzyy** [comment]
@plata Unfortunately #427 is not fixed.
