### ISSUE TITLE
Containers don't get removed from view until restart of app after uninstall

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#467]

**Comment by Brainzyy** [comment]
@plata The container now gets removed from the list on the left, but on the main container screen it still show the info about the container that was removed, instead of the normal "Please select container to configure" message.

**Comment by Brainzyy** [comment]
![This](https://cloud.githubusercontent.com/assets/8126341/21955438/874a7bde-da6b-11e6-8c2a-d1c412940c3e.png)
instead of:
![this](https://cloud.githubusercontent.com/assets/8126341/21955440/93533f38-da6b-11e6-9e2c-b976cdd04477.png)

**Comment by plata** [comment]
@Brainzyy please create a new issue for this.

**Comment by Brainzyy** [comment]
@plata alright.
