### ISSUE TITLE
Container main window doesn't get refreshed after uninstall

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#469]
![This](https://cloud.githubusercontent.com/assets/8126341/21955491/91836b1e-da6c-11e6-9769-b48aace57c3a.png)
instead of:
![this](https://cloud.githubusercontent.com/assets/8126341/21955494/9d600f78-da6c-11e6-99e7-627af2673111.png)

**Comment by plata** [comment]
@Brainzyy does it work if you add
```java
initSelectContainerPane();
```
to `populate()` in ViewContainers.java?

**Comment by Brainzyy** [comment]
@plata That does not work.

**Comment by plata** [comment]
@Brainzyy can you try if it's fixed?

**Comment by Brainzyy** [comment]
@plata Confirmed fixed.
