### ISSUE TITLE
App hangs when switching from and to containers

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#470]

**Comment by qparis** [comment]
@plata It seems to be caused by your commit

**Comment by plata** [comment]
What exactly is the problem (how do I reproduce)?

**Comment by qparis** [comment]
Click on the "Container" button. It does not appear directly and the interface lags

**Comment by plata** [comment]
Sorry but I do not have that behavior.

**Comment by qparis** [comment]
You do not have enough containers

**Comment by plata** [comment]
I think it is because WinePrefixesManager `fetchContainers()` accesses the file system to get the container information. Therefore it reads the cfg in all prefixes.

**Comment by qparis** [comment]
And all the registry files yes. This is why it should not be synchroneous

**Comment by plata** [comment]
How is it done for the apps? They have to be fetched as well.

**Comment by qparis** [comment]
This is already asynchroneous (See BackgroundApplicationSource)

**Comment by plata** [comment]
Ok. So the task here is: Implement BackgroundContainersManager for asynchronous fetching of containers (see BackgroundApplicationSource).

**Comment by qparis** [comment]
I guess it is yes

**Comment by plata** [comment]
I started but I'm stuck. Do you mind having a look?

**Comment by qparis** [comment]
No problem

**Comment by plata** [comment]
Think I found it already :P

**Comment by plata** [comment]
@qparis I think this can be merged for now, right?

**Comment by qparis** [comment]
Uzs

**Comment by qparis** [comment]
Yes *
