### ISSUE TITLE
[Themes] Fix HDPI theme

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#485]

**Comment by plata** [comment]
For which resolution shall it work? I have 2560x1440. The sizing of the default and dark theme is pretty ok for that. Only application names could be a bit bigger.

**Comment by qparis** [comment]
What is the size of you screen? 
This CSS is not finished, but it desgined for HDPI (Retina) display which have a resolution of 2880*1800 on a 15" display. 
On MacOS, the apps are automatically scaled. This is not true on linux in general

**Comment by plata** [comment]
I have 24''. So everything is a lot bigger that on 15'' 2880x1800. What about "regular" 4k?

**Comment by qparis** [comment]
You have a full hd screen, not HDPI. This is why it looks very big

**Comment by plata** [comment]
No. Full HD is 1920x1080. Mine is usually called something like UHD.

**Comment by qparis** [comment]
Yeah, my point is hdpi is even denser

**Comment by plata** [comment]
Sure. I was just asking because some applications are messed up with UHD already.

**Comment by plata** [comment]
Can we close this? I think it is superseded by #612 and #711.
