### ISSUE TITLE
Small white line below left image in step representation

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#496]
![white line](https://cloud.githubusercontent.com/assets/3973260/22177861/35728ce0-e027-11e6-9b22-2b6cd7bc5833.png)

**Comment by qparis** [comment]
This is expected. However, the color should be customizable

**Comment by plata** [comment]
Do you know what has to be changed to customize it?

**Comment by qparis** [comment]
I think it is a border in one or the SetupwindowStepRepresentation classes

**Comment by qparis** [comment]
#footer {
    -fx-border-color: #CCCCCC;
    -fx-border-style: solid;
    -fx-border-width: 1px 0 0 0;
}

**Comment by plata** [comment]
I will have a look once #499 is merged.
