### ISSUE TITLE
Let scripts do process handling

### ISSUE THREAD

**Issue by seijikun** [PlayOnLinux/POL-POM-5#498]
Hey guys, nice to see so much activity!

With POL4 (in my memory), it often happened that POL told you; your app just crashed, and then suddenly the game opened just fine. I guess that is because the process that was started initially (the launcher) exited after having launched the game's actual binary.
One example of this is Diablo II, I think.

An idea I head some time ago was the following:
Maybe it was feasible to let scripts do the process starting / controlling. There could be a default implementation that does just what is done now, which could then be optionally overwritten.

In cases like Diablo II, the script could start the launcher process, get the child's PID when the launcher exited and wait for this process to die.
We sure would have to export some API for this and I'm not completely sure if this is even possible.
Just an idea!

**Comment by qparis** [comment]
It is already possible :)

**Comment by seijikun** [comment]
Really? Is there an example script already making use of this?

**Comment by qparis** [comment]
wine script has a .wait() and a .kill() method. It should also be possible to get the PID of the process

**Comment by seijikun** [comment]
Is it currently also possible to spawn multiple window binaries within one wine engine process?

**Comment by qparis** [comment]
Should be. I haven't tried though

**Comment by seijikun** [comment]
Oh ok. You can probably close the issue then.
I have missed out on many aspects, it seems.
