### ISSUE TITLE
[Themes] Make icons part of the theme

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#501]
We should use the system icon scheme to better integrate with the look and feel.

**Comment by qparis** [comment]
I do not agree for some reasons:
* It is hard to ensure that all skins will look good with all sets of icons 
* We do not really have a concept of "system icons" on OSX  
* Eventually, I think the icons should be customizable in the skins

**Comment by plata** [comment]
Ok. Making it customizable in the theme is also fine.
