### ISSUE TITLE
Ubuntu theme needed

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#526]
Incorrect theming of the scrollbar on the right, it should look like this (in Ubuntu's default theme):
![screenshot from 2017-01-23 18-03-42](https://cloud.githubusercontent.com/assets/3178485/22216302/7136c0be-e196-11e6-93f6-3474ee6f6631.png)

not this:
![screenshot from 2017-01-23 18-04-14](https://cloud.githubusercontent.com/assets/3178485/22216305/75b6e5a6-e196-11e6-8572-cf4ea03f270e.png)

Also incorrect colour for buttons etc.

Ubuntu 16.10

**Comment by plata** [comment]
The number of columns should increase already. Here's how it looks for me:
![columns](https://cloud.githubusercontent.com/assets/3973260/22216462/8216bca0-e19f-11e6-8676-99d173b3f66c.png)

Regarding the scrollbar: It depends on the theme. The default PoL theme does not theme the scrollbar in any special way, so the default Java theme is used. There is a Breeze Dark theme which tries to integrate with Plasma 5. You might try to create a theme which matches the Ubuntu look and feel.

**Comment by Ads20000** [comment]
Yeah the theming in general does not match Ubuntu's like POL 4's one does. I'm not very technical I just thought I should follow the compiling instructions on Ubuntu and see what happens, so I don't think I'll be able to make my own theme!

**Comment by plata** [comment]
In case you want to give it a try: here's a description in the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Themes). Otherwise you will have to live with the available themes until someone does the theming for Ubuntu ;)

**Comment by Ads20000** [comment]
OK, I forgot I hadn't updated recently, I did a `git pull` and now the icon issue is resolved, the theming one isn't so I'll leave that

**Comment by plata** [comment]
I would prefer if you could open a new issue for the Ubuntu theme request.

**Comment by Ads20000** [comment]
Done, see #529 , thanks for the help!
