### ISSUE TITLE
Nothing happens when clicking on the thumbnail of an engine

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#528]
Presumably this is meant to do something, like give me a progress bar whilst it installs or something.

Ubuntu 16.10

**Comment by plata** [comment]
You should see something like:

![container](https://cloud.githubusercontent.com/assets/3973260/22216959/6e576208-e1a1-11e6-942c-f8545cb889e8.png)

Do you get any error output when you run PoL from the console?

**Comment by plata** [comment]
I guess this is also fixed after a pull?

**Comment by Ads20000** [comment]
Urgh sorry about that, I meant *engine. Maybe nothing is supposed to happen? But then why is the screen even there? I can't see anything in Terminal is there a way I can produce more verbose Terminal output?

**Comment by Brainzyy** [comment]
@Ads20000 This is supposed to be like that. The screen is there to help users and script creators know what engines are available for usage.

**Comment by Ads20000** [comment]
That seems very odd to me, because it doesn't look like there's an option to change the Wine version of a container and it doesn't look like it's possible to manually install programs with POL like you could in POL 4. And having that list in the consumer-facing app just for developers seems silly!?

**Comment by qparis** [comment]
This component is not finished yet

**Comment by plata** [comment]
@qparis can you describe what the functionality of the "Engines" tab shall be?

**Comment by qparis** [comment]
Install and remove wineversions basically

**Comment by plata** [comment]
I'm trying to install a wine version from Java but the JS Wine expects a wizard which does not exist.

**Comment by qparis** [comment]
We can create a different adaptation of wizard specially adapted for the engine tab

**Comment by plata** [comment]
Ok. I will open some issue for this.

**Comment by plata** [comment]
Superseded by #614, #615, #617.
