### ISSUE TITLE
[Themes] Theme doesn't change

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#536]
Theme doesn't change immediately after selecting a theme and pressing `Save`. I would expect it to change immediately.

![Unity theme...but it's not](https://cloud.githubusercontent.com/assets/3178485/22398522/1289a3f2-e582-11e6-823f-0c4a816feb73.png)
![Dark theme...but it's not](https://cloud.githubusercontent.com/assets/3178485/22398523/1340971a-e582-11e6-9507-39343089d20c.png)

**Comment by qparis** [comment]
POL needs to be restarted so that the properties and the CSS are refreshed properly

**Comment by Ads20000** [comment]
Unless if there was some text saying 'you need to relaunch PlayOnLinux to use the selected theme', then I would not expect it to happen immediately

**Comment by Ads20000** [comment]
Yeah, I think you need some text saying that.

**Comment by plata** [comment]
It's not supposed to stay like this.

**Comment by qparis** [comment]
I think we should not have any save button at all

**Comment by plata** [comment]
Yes. And we need the ThemeManager to change the theme on the fly.
