### ISSUE TITLE
No option to delete containers

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#539]
There should be an option to delete containers/apps, but there isn't.
(This might just be missing functionality, but it's functionality a user would expect to be there so I'm filing it anyway as a to-do task)

**Comment by plata** [comment]
If you select the app in the library, there is a button on the left to uninstall. This will also allow you to delete the container.

**Comment by qparis** [comment]
Yeah but @ads20000 is right, we need all available options of POL4 in container tab :-)

**Comment by Ads20000** [comment]
@plata It relates to #540, of course it would best if the install scripts 'just worked' and existed for every Windows application in existence, but if you're manually installing different apps and have several different containers using different versions of Wine etc (because you think it too risky to change the version of Wine inside an existing container) then you'll want an option to delete POL containers.

Perhaps there should be an option to clone a container too for this sort of experimentation with Wine versions etc. Ideally a user would never have to go to the container screen, but this is for manual customisation when the automatic install scripts fall short.

Thanks again for considering what I have to say in these issues!

**Comment by Ads20000** [comment]
@plata Another thing to consider: In POL 4 you're able to have several apps using the same container, so deleting an app doesn't delete a container. I suppose if it's only one app to one container in POL 5 then you're right, there shouldn't be an option to delete containers, but I think people should have the option to use different containers with different Wine versions and Winetricks to try and get an app to work (and then they should be encouraged to write a script using the working combination!) But if this is the case you'll need to decide how different containers with the same application surface their application launchers in the Library.
