### ISSUE TITLE
Easy-to-use manual installation screen needed (missing POL 4 feature)

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#540]
Like in POL 4, would be nice if there was an option somewhere to manually install an app with the Wine version you want to use and with your own Winetricks options. Should be possible to change the Wine version of (and Winetricks used in) a manually installed app as well (you could keep it uneditable for an app installed with a script so that a user doesn't try to bump the Wine version number thinking it will help them).

**Comment by plata** [comment]
Actually, we could provide simple wrappers for OnlineInstallerScript, LocalInstallerScript, SteamScript and QuickScript in a "Custom" category. Every time user input is needed, they would just show e.g. a file dialog.

**Comment by Ads20000** [comment]
The text box to type in the name of the program is invisible (on the Ubuntu theme at least), I can see it when I hover over it but at first, because I couldn't see it, I thought I had to type the name in the search box top-left!

![screenshot from 2017-02-01 14-05-11](https://cloud.githubusercontent.com/assets/3178485/22509836/9149a784-e887-11e6-89da-e45092b17f4a.png)

**Comment by Ads20000** [comment]
Oh and instead of producing an error, if I put no name in it allows me to continue anyway which is probably a problem?
![screenshot from 2017-02-01 14-07-22](https://cloud.githubusercontent.com/assets/3178485/22509897/c8dbf472-e887-11e6-9d0f-3c52de1d9046.png)

**Comment by Ads20000** [comment]
Then, when I click Cancel, it says 'the script ended unexpectedly' in a popup, which is annoying because I told it to exit. Further, when I click show details it doesn't expand the window nicely to fit in the details box and when I maximise and then hide the details box it doesn't automatically reminimize like, say, the Software Updater on Ubuntu would. If I expand the details box again it looks really nasty. I don't think a box should appear in this case anyway, but presumably the same problems apply when a script genuinely crashes.

![screenshot from 2017-02-01 14-08-27](https://cloud.githubusercontent.com/assets/3178485/22509968/22f87c96-e888-11e6-8565-b8f9fe43e20a.png)
![screenshot from 2017-02-01 14-08-34](https://cloud.githubusercontent.com/assets/3178485/22509969/2319fdc6-e888-11e6-8d1d-a7f4c030cb45.png)
![screenshot from 2017-02-01 14-10-43](https://cloud.githubusercontent.com/assets/3178485/22510006/464a0c0a-e888-11e6-9526-e9cbb4f3bb73.png)
![screenshot from 2017-02-01 14-10-52](https://cloud.githubusercontent.com/assets/3178485/22510007/4763c040-e888-11e6-9441-4062b932484f.png)

**Comment by Ads20000** [comment]
Also instead of a download URL it should accept local files, I can't get a download URL for Office 2013, I need to be able to point the installer to a local file. Because of this, I'm going to have to use POL 4 to install it for now, I don't know what direct link I need to install Office.

**Comment by plata** [comment]
@Ads20000 I have implemented your remarks (hope I didn't forget one).

For the error message when canceling the installation, please see #403.

**Comment by plata** [comment]
@Ads20000 can we close this?

**Comment by Ads20000** [comment]
@plata I also need the option to change Wine settings when installing, I can't install Office 2013 unless I change the Wine version to Windows 7+
