### ISSUE TITLE
Change wiki to reflect new changes (phoenicis.sh doesn't work anymore to run the program)

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#558]
If I'm saying or doing anything stupid, please tell me.
It says 'cannot find main class JavaFXApplication' when trying to run phoenicis.sh.
Can it only be installed with the .deb now?

**Comment by plata** [comment]
There was a mistake in the script. No idea how this could happen. Thank you for pointing it out. :+1:
