### ISSUE TITLE
Phoenicis extremely slow on installing software, unlike POL 4

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#570]
I was trying to manually install Microsoft Office 2013 and the screen froze for a rather long time with the computer 'thrashing the hard disk' for ages. Eventually, after switching to `tty1` and back a few times, it unfroze enough for me to close Phoenicis once Office 2013 had brought up the screen complaining about the Windows version. In POL 4, I don't get this freeze or lengthy hard disk thrashing at all.

I've also tried to install AoE II with a similar effect

[Terminal output.txt](https://github.com/PlayOnLinux/POL-POM-5/files/754666/Terminal.output.txt)

**Comment by plata** [comment]
I'm not quite sure but maybe it's when fetching the scripts from GitHub. Could you try to clone the [Scripts](https://github.com/PlayOnLinux/Scripts) repository on your PC and then change the settings such that it's using only the local repository? To do so: Settings → Repositories → clean everything, then add `file:///home/<you>/<path_to_your_scripts_clone>`.
However, the scripts repository is quite small, so it should not really cause trouble.

The other stuff in the log is only output from the wine installation. You should not get it again when you install anything using the same wine version.

**Comment by plata** [comment]
@Ads20000 do you still have this issue?

**Comment by Ads20000** [comment]
@plata Can you ping me again Thursday evening GMT? #LastMinuteEssay

**Comment by plata** [comment]
@Ads20000 ping

**Comment by Ads20000** [comment]
Hmm, well I've already got a MS Office 2013 container (with Wine 2.0) installed which I was using to try and get that to work (it didn't), but then I tried to install Age of Empires II HD and it works great (after renaming the AoK HD.exe launcher to Launcher.exe (and adding .bak to the original Launcher.exe). However, it did nearly freeze up my computer at one stage, unfortunately I can't remember when. Was thrashing my disk like crazy for ages (which didn't happen with POL 4).

Have a log... http://paste.ubuntu.com/24130439/

**Comment by plata** [comment]
Strange. Cannot really see anything weird in the log. If it was only with Steam games, it could be because the SteamScript is polling the installation status.
Would be really helpful to know when the high disk usage occurs (and by which program). Could you try again and observe the disk usage in your system monitor?

**Comment by Ads20000** [comment]
Disk usage isn't in Ubuntu's default system monitor but I tried `sudo iotop` and `[loop18]` was high on `DISK READ` towards the end of downloading Steam - and it froze a bit. Then `Steam.exe~all/221380` was thrashing the disk when it froze a bit then. Now it's completely locked up with `java -cla~pplication` thrashing the disk before it froze. I can get the longer process names if I retry and expand the Terminal window?

**Comment by plata** [comment]
Don't longer process names are necessary. The first one will be `Steam.exe steam://install/221380`, the second `java -classpath "xyz" org.phoenicis.javafx.JavaFXApplication`. We cannot do anything about the first one (it is Steam itself). Maybe the approach to show the Steam download progress is causing this. Could you comment the whole block below in `Functions/QuickScript/SteamScript/script.js` and try again?
```Javascript
   var bytesToDownload = this.getBytesToDownload(wine);
    var bytesDownloaded = 0;
    var progressBar = setupWizard.progressBar("Please wait until Steam has finished the download...");
    while (bytesDownloaded < bytesToDownload)
    {
        bytesDownloaded = this.getBytesDownloaded(wine);
        progressBar.setProgressPercentage((bytesDownloaded / bytesToDownload) * 100);
        progressBar.setText("Downloaded " + bytesDownloaded + " of " + bytesToDownload + " bytes");
        java.lang.Thread.sleep(100);
    }
```

**Comment by Ads20000** [comment]
@plata where do I find this directory?

**Comment by plata** [comment]
You need to clone the [scripts repository](https://github.com/PlayOnLinux/Scripts) (also see [wiki](https://github.com/PlayOnLinux/Scripts/wiki/Best-practices).

**Comment by Ads20000** [comment]
@plata So I cloned and commented out that bit. Does Phoenicis automatically prioritise the local repo over the GitHub one? I got up to a bit where it said 'Please wait...' and `java -classpath "xyz" org.phoenicis.javafx.JavaFXApplication` locked up my computer again.

**Comment by plata** [comment]
It depends on the order you specify the repositories in the properties file. I'm using a `config.properties` in `..Phoenicis` which contains:
```
application.repository.configuration=file\:///home/plata/.Phoenicis/repository/;
```
So I'm not using the GitHub repository at all.

You can find more info regarding this [here](https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository).

**Comment by Ads20000** [comment]
After I added that `config.properties` file (and changing `plata` to my username), still thrashing my disk really bad and freezing my mouse when it gets to 'Please Wait' after I check the checkbox to not open Steam after I install it and close that window.

**Comment by plata** [comment]
If you also did the changes in `SteamScript` which I`ve described above, the only thing that should happen at that point is the Steam update. Could you check if you get this behavior with applications that do not use Steam (e.g. Notepad)? To be honest, I'm running out of ideas what could cause this (especially because no one else seems to have this issue).

**Comment by Ads20000** [comment]
I tried installing Notepad++, nothing notable in `iotop` but `java` was 80% CPU before falling and then taking up 80% RAM. Was very slow to install, freezing my mouse etc and got to the end but when I unchecked launch after exit and tried to close that window my computer froze.

It's irritating because I don't have this issue in POL 4. I love POL and want up-to-date POL but my computer doesn't seem to be able to handle this Java incarnation of POL.

**Comment by Ads20000** [comment]
Also, I'm using `git pull` to update, maybe that doesn't update properly? I could do a fresh clone?

**Comment by plata** [comment]
Maybe give it a try. But honestly this behavior is really strange. Especially Notepad++ usually installs in a view seconds without any problems. Are you sure your computer is alright? How about other Java applications?

**Comment by Ads20000** [comment]
I tried Minecraft, was disk-thrashy and slow until I turned the graphics down then it was fine. @plata when you install Notepad++ how much CPU and RAM does it use up for you? And has someone with lower specs like mine (Lenovo ThinkPad X201 (i5 520-M (2.40GHz*4), 4GB RAM), Ubuntu 16.10) given it a go?

I'm using OpenJDK 8u121-b13-0ubuntu1.16.10.2. OpenJDK 8u121 is what, generally speaking, people will be using on Ubuntu and the easiest to depend on in a Deb package or a Snap. I can try Oracle Java too if you want?

**Comment by Ads20000** [comment]
OK, it does use a lot of my CPU, like around 300% (I'm assuming it's talking in terms of cores, so it can go up to 400%? Using `top`), and 200% or so whilst playing at 10fps with higher graphics. More like 40-80% when playing with more minimal graphics. But I don't get a complete freeze of my computer that I get with Phoenicis!

**Comment by plata** [comment]
Just installed Notepad++. I had a CPU load peak on one core right at the beginning (I guess when the prefix was created). After that, all cores around ~10-20%. Could not see any memory increase during installation (when closing Phoenisic ~500MB got freed).

I'm on Ubuntu 16.04 so some OpenJDK like you.

**Comment by plata** [comment]
@Ads20000 any new on this?

**Comment by Ads20000** [comment]
@plata I'll have good Internet again tomorrow, at the moment it's not good enough to test (1mbs eek!), remind me again tomorrow? :)

**Comment by plata** [comment]
@Ads20000 bump

**Comment by Ads20000** [comment]
@plata Successfully installed Age of Empires II HD on a clean Phoenicis `git clone` and I deleted the hidden folders in `~`. Either you fixed it or I just needed a clean install. Cheers for following up on this!
