### ISSUE TITLE
PlayOnLinux 5 suggestions which wine should be used.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#581]
When i install application non-script i see too much wine version (PlayOnLinux 4). 
New user does not know, nothing about wine.

In my opinion must be divide, something of a kind.
- stable (recommend)
- devel (not recommend)

I am only user and it is only suggestion.
Please, you must add this feature :)

**Comment by plata** [comment]
There is already a division in
- upstream (what you call stable)
- staging (what you call devel)

**Comment by qparis** [comment]
This is not really the same things

**Comment by pyroxar** [comment]
Ok, staging or not. Now it is not clear. Wine in PlayOnLinux5 must be better described.

**Comment by plata** [comment]
We could probably select the current stable version by default if that would help you.

**Comment by pyroxar** [comment]
And should be written "Last stable" or "recommended for most users". More user experience and be ok.

**Comment by plata** [comment]
For the "recommended" I see two options:
1. We just add it to the text in the ListView and remove it from the selected result before passing it to wine. Easy, but quite a hack. Might also cause problems with translations.
2. We implement a custom cell factory with an additional description text. Would probably require to populate the ListView with beans from javascript. Make the interface too heavy in my opinion.
