### ISSUE TITLE
Wording: container, prefix

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#599]
Is there any difference between a "container" and a "prefix"?

If not, the wording should be unified.

**Comment by qparis** [comment]
A prefix is a technical term and a container is a marketing term.

A wineprefix is a kind of container

**Comment by plata** [comment]
Do you think container is more understandable than prefix? I think it will cause confusion if we have a container which is a prefix which is a bottle.

**Comment by qparis** [comment]
Yes a prefix does not make any sense for other stuff than wine I think

**Comment by plata** [comment]
Can't we call the wine prefix "wine container" then? We have a WineContainerController which controls a WinePrefixContainerPanel and WinePrefixDTOs. When we get other containers than wine, there will be a WinePrefixDTO and a xyContainerDTO which in fact both describe a kind of container.

**Comment by qparis** [comment]
It depends on the place. If you are taking about the interaction between the script and wine, it's better to talk about prefixes.
If you are talking about the way POL sees the different prefix, it is more appropriate to talk about container.

The two concept are differents but design the same thing.

**Comment by plata** [comment]
I get your point. However, I think that this is quite confusing. Obviously, it should be WineContainerPanel instead of WinePrefixContainerPanel. For the DTO it's impossible to say because it's used in both concepts.

**Comment by plata** [comment]
What about using Wine prefix everywhere and just saying that a Wine prefix is a certain kind of container? That should be easy to understand for everybody.

**Comment by qparis** [comment]
Yep, this is what I had in mind

**Comment by plata** [comment]
So: WinePrefixContainerPanel → WinePrefixPanel, WineContainerController → WinePrefixController?

**Comment by qparis** [comment]
I would say WinePrefixContainer*
