### ISSUE TITLE
Mark installed engines

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#602]
E.g. by adding a green check
![installed](https://cloud.githubusercontent.com/assets/3973260/23078858/ad4a76e6-f54a-11e6-9307-9c90f0428a81.png)

**Comment by qparis** [comment]
Or by outing in black and white non installed versions

**Comment by plata** [comment]
That would also be great!

**Comment by plata** [comment]
Code for the gray scale:
```Java
ColorAdjust grayscale = new ColorAdjust();
grayscale.setSaturation(-1);
engineItem.setEffect(grayscale);
```
