### ISSUE TITLE
WineVersionDTO incomplete

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#613]
The WineVersionDTO contains incomplete information about the engine. E.g. we cannot know the architecture/distribution as this is only contained in the WineVersionDistributionDTO. For the installation/deletion, also the architecture and distribution must be known. As we cannot pass two DTOs in the Consumer, we have a problem here.

**Comment by qparis** [comment]
It is not incomplete because it is a children of WineDistributionDTO

What you neee is a new kind of DTO

**Comment by plata** [comment]
How should that new DTO look like without duplicating information from the WineVersionDistributionDTO and the WineVersionDTO?

**Comment by qparis** [comment]
This is not a problem to duplicate information. This is not the same data structure

**Comment by plata** [comment]
How should it be done?

**Comment by qparis** [comment]
You could create a new set of DTOs

**Comment by plata** [comment]
In which folder? What content? How should they be named?

**Comment by qparis** [comment]
What module are they going to be used to? What data do you need?

**Comment by plata** [comment]
Should be used in the Engines(Controller) to install/delete engines. In the case of wine, I need version, distribution and architecture to identify the correct wine version (or a JS Wine object).

**Comment by qparis** [comment]
Then, a WineEngineDTO in the same module should be a good start. You can add the information you need as strings

**Comment by plata** [comment]
Why not in phoenicis-engines?

**Comment by qparis** [comment]
Yep, can be :)

**Comment by plata** [comment]
fixed in #616
