### ISSUE TITLE
Implement engines wizard

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#617]
A new wizard implementation for the engine installation. Required by #614.

**Comment by plata** [comment]
@qparis would it be possible to extend the setupWizardFactory by a new parameter describing the type of installation (e.g. "app" or "engine"). The setupWizardFactory should then determine where the new tab for this wizard has to be created.

**Comment by qparis** [comment]
There is not reason to do this, we should just inject another SetupWizardFactory

**Comment by qparis** [comment]
My mistake, it is even not required. The SetupWizard can be instanciated in Java and injected directly

**Comment by plata** [comment]
Yes but it will show up as tab in the library. I'm not so sure this is good. Just one second and I'll show you what I have in mind.

**Comment by qparis** [comment]
The SetupWizard interface does not require a new tab. JavaFxSetupWizard implementation do

**Comment by qparis** [comment]
SetupWizard is way more abstract than that. You can show it wherever you want as long as the methods are implemented

**Comment by plata** [comment]
Have a look at the PR. I'm completely reusing the existing JavaFX wizard implementation (not only the SetupWizard interface). With this approach, I could even implement the install/delete for any engine directly in JS.
