### ISSUE TITLE
Slow wine download

### ISSUE THREAD

**Issue by feanor12** [PlayOnLinux/POL-POM-5#621]
I ran an OnlineInstallerScript and it works fine, but the wine download is really slow.

This is the URL it downloads from(takes 6 hours):
http://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/PlayOnLinux-wine-2.0-upstream-linux-x86.tar.gz

**Comment by plata** [comment]
Seems like playonlinux.com has some issues currently. This is not normal.

**Comment by feanor12** [comment]
Seems to be fixed
