### ISSUE TITLE
Show Play on Linux 5 version

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#629]
Is there a way to see the current Play on Linux 5 version in the javafx gui client?
I believe it would be useful to have a window that shows your current version and maybe also an information if a newer version is available.

**Comment by feanor12** [comment]
I think it's possible to get the git revision with maven. So it should be possible to show it. Maybe a version file?

**Comment by plata** [comment]
I think we can add the version to the existing properties files.

**Comment by plata** [comment]
What do you think?
![about](https://cloud.githubusercontent.com/assets/3973260/23579081/c658a8be-00e5-11e7-88ca-28a5b95d6716.png)

**Comment by qparis** [comment]
Like

**Comment by madoar** [comment]
Looks quite nice, but I think it's missing a build date and maybe the commit, at least while POL5 isn't released.

**Comment by plata** [comment]
Could use [Build Number Maven Plugin](http://www.mojohaus.org/buildnumber-maven-plugin/usage.html) for that.

**Comment by feanor12** [comment]
I think the git revision id would be nice.
