### ISSUE TITLE
Using the .deb file to install and update Play on Linux 5

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#631]
I've installed Play on Linux 5 with the .deb file that maven created for me. 
Now I want to update POL 5. Is it correct to assume that POL 5 can be updated by reinstalling it with a newer .deb file?
With newer I mean created via maven clean package after using `git pull`.

**Comment by plata** [comment]
Not sure if it will update by default (because the version did not change). But you should be able to force it.

**Comment by plata** [comment]
Can we close this? (I don't think there is anything we could do about the behavior of apt etc. when installing .deb's)

**Comment by madoar** [comment]
This is quite interesting, because the installer doesn't even tell me that the software is already installed on my system. It just says that all dependencies are fulfilled and that I can install POL 5, even if it is already installed and even if it's the same version.
I'm not sure if this issue should be closed, I would use this issue at least as a reminder to update the installation instructions to add a short paragraph about using the .deb file to install POL 5.
What do you think?

**Comment by plata** [comment]
If it's about the wiki description, we should change that and then get rid of this issue. I don't know if you have the rights to update the wiki. Otherwise tell me how I should change it and I will do it.

**Comment by plata** [comment]
@madoar I would like to close this. As stated above, please propose how I should change the wiki such that it's clear.

**Comment by madoar** [comment]
I've just written a small article about the installation (at least for ubuntu based systems) see https://github.com/PlayOnLinux/POL-POM-5/wiki/Installation.
What do you think?

**Comment by plata** [comment]
The other wiki pages use "you" or "do this/do that". I think you should stick to that (instead of "the user should..."). If it's true that you have to install Java 8 first, we should fix the dependencies of the deb instead of writing this to the wiki.

**Comment by madoar** [comment]
Can you fix the Java 8 dependencies? I don't know how.
I suggest that we change the wiki article afterwards, what do you think?

**Comment by plata** [comment]
It's in `phoenicis-dist/src/deb/control/control`. `java8-runtime` is listed there already. Or is `default-jre` not Java 8 in Ubuntu 16.04?

**Comment by madoar** [comment]
I think it's missing javafx.

**Comment by plata** [comment]
see #741
