### ISSUE TITLE
Show all categories by default

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#632]
After entering the `Apps` tab and inputing a search keyword you will see no search results, because no categories are selected:
![grafik](https://cloud.githubusercontent.com/assets/18488086/23579425/2e8ad9f0-00ed-11e7-8a53-519904cfa61e.png)

To see results you need to select at least one of the categories on the left side:
![grafik](https://cloud.githubusercontent.com/assets/18488086/23579426/39483e50-00ed-11e7-8d99-39da14ba86c2.png)

I would suggest to show all categories by default, because it's more intuitive then and otherwise the user may think that no scripts for the given keyword were found.

**Comment by plata** [comment]
I thought that the code below (for AppsController) should work. But somehow it doesn't.

```Java
this.view.setOnApplyFilter(filter -> {
    appsSource.setFilter(filter);
    appsSource.fetchInstallableApplications(categories ->
            {
                this.view.populate(categories);
                List<ApplicationDTO> foundApps = new ArrayList<>();
                for (CategoryDTO foundCategory : categories) {
                    foundApps.addAll(foundCategory.getApplications());
                }
                this.view.populateApps(foundApps);
            },
            e -> this.view.showFailure()
    );
});
```
