### ISSUE TITLE
Highlight current software category

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#633]
When I select a category in the `Apps` tab, I don't know which category I've selected. I think it would be nice to highlight it somehow. Maybe with a different background color of the selected category label?

**Comment by plata** [comment]
This is now the 3. (or so) issue requesting this. When I opened an issue for this initially, @qparis explained to me that we should not do that for the following reason: If you search and show all found apps on the right, highlighting a certain category doesn't make sense.

However, to me this issue is just a proof that this concept is not clear at all. Maybe we should always have a selected category (actually the search works like this currently) and not show apps from different categories on the right (as requested in #632).

**Comment by madoar** [comment]
I didn't mean to say that a category must be always selected. I just wanted to say that the currently selected category is not made visible.
Here is an example:
![grafik](https://cloud.githubusercontent.com/assets/18488086/23580413/b18e59a8-0101-11e7-9dcd-42977d29b8fd.png)
Where do I see which category is currently selected? (The answer is "Games")

**Comment by plata** [comment]
I don't think it makes sense to have a button which sometimes behaves like a Button and sometimes like a ToggleButton.

If you would like to see how it looks like with a ToggleButton, just replace `LeftButton` with `LeftToggleButton` in `ViewApps#populate`.

**Comment by plata** [comment]
Just looked at muon to see an example how a search with categories could be done. Actually, it's pretty obvious... If we would add a category "All", we could use ToggleButtons and show all found applications.

**Comment by qparis** [comment]
My mistake

**Comment by qparis** [comment]
I think we could have a search result category

**Comment by plata** [comment]
Don't think that's a good solution. Imagine you have a lot of results and want to see only e.g. games.

**Comment by madoar** [comment]
I agree with @plata. I would suggest to view the search input as an extension to the selected categories.
I think every application should be shown that:

1. is contained in at least one of the selected software categories and
2. contains the search keyword either in its name or in its description

**Comment by plata** [comment]
Currently, the search shows results from all categories if the app name contains the search string. I think it's fine this way.
The position of the search bar suggests that the search is not related to the currently selected category. If you want to see the results only for a certain category, you can still select the category after the search.
If we would search in the descriptions as well, you would get results you do not expect at all (so people would believe that the search is broken). As you do not see the description directly, it's absolutely not obvious why a certain app is shown in the search if only the description contains the search string.

In my opinion this issue should be closed.

**Comment by madoar** [comment]
For me this issue is fixed, should I close the issue?

**Comment by plata** [comment]
Yes, please.
