### ISSUE TITLE
Bad color choice for header texts in the Dark theme

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#634]
When using the "Dark theme" the header texts in the left sidebar like "Settings" above "User Interface" in the following screenshot are written in black, which is really hard to read with the dark background color:
![grafik](https://cloud.githubusercontent.com/assets/18488086/23580589/df97e4ce-0104-11e7-8764-9faa5508b417.png)

**Comment by plata** [comment]
If you want to change this, there is a tutorial about themes in the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Themes). For this particular case, you need to change `leftBarTitle` in phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css.
