### ISSUE TITLE
Missing libncurses.so.5

### ISSUE THREAD

**Issue by feanor12** [PlayOnLinux/POL-POM-5#643]
If I start pol5 on the command line I get
`Wine cannot find the ncurses library (libncurses.so.5).`

**Comment by plata** [comment]
How did you install? Using the .deb? If so, the dependency is missing in the .deb creation.

**Comment by feanor12** [comment]
I installed it via https://aur.archlinux.org/packages/playonlinux5-git/
which uses phoenicis-dist.zip.

**Comment by plata** [comment]
Do you have any system wine installed (apart from the versions installed through Phoenicis)?

**Comment by feanor12** [comment]
yes wine-staging 2.3-1.
I get this error once when I started pol5( doing nothing else) and every time when I start a wineshortcut.

**Comment by plata** [comment]
Your wine-staging package should have the ncurses dependency.

**Comment by feanor12** [comment]
I just noticed that the _ldPath property is not set in the Wine.run method. Shoud this be engines/wine/version/lib ?

**Comment by plata** [comment]
It definitely needs to consider 32/64bit. Apart from that I'm not even sure how it works currently. Also, that folder does not contain ncurses so it should take the system one.

**Comment by Lchu613** [comment]
I fixed this problem by installing ncurses5-compat-libs and lib32-ncurses5-compat-libs; I think it occurs because ncurses newest version is 6, but wine still wants to use version 5.

**Comment by feanor12** [comment]
I will try to verfiy this. I searched for ncurses 5, but could not find the correct package.
If pol should work on all systems, I think we should include all libraries though.

**Comment by plata** [comment]
Thanks a lot. Maybe it's just a missing dependency in the .deb. If you can verify this, please add it to #741.

**Comment by feanor12** [comment]
I installed the packages mentioned above and I can verify that the message

> Wine cannot find the ncurses library (libncurses.so.5).

does not show. When uninstalling the packages the message shows up again.

**Comment by madoar** [comment]
@plata is there anything we can do about this issue?

**Comment by plata** [comment]
I'm not sure (I don't know how it should behave). @qparis how was it in PoL4? Did it use the system libs or was the path set to the specific lib folder of the wine version?

**Comment by madoar** [comment]
@qparis And this? :)

**Comment by qparis** [comment]
Shouldn't it be a dependency?

**Comment by plata** [comment]
@qparis as I said above: I don't know how it was handled before. As ncurses seems to be part of every Wine installation, it would make sense to adjust the PATH. If we want to use the system ncurses, we do not have to deliver it as part of Wine.
