### ISSUE TITLE
Add "clear" Button for the search input textfield

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#645]
To clear a search textfield, that is available in the four tabs "Library", "Apps", "Containers" and "Engines" it's currently needed to manually delete the text inside the search field. I believe it would be more comfortable to add a clear button right next to the textfield, which clears the content of the textfield after a click onto it.

**Comment by plata** [comment]
I don't like a separate button next to the text field (wastes too much space). I think it is enough to clear the search box when you click it ([how to](https://stackoverflow.com/questions/28516654/javafx-how-to-clear-textfield-when-mouse-is-clicked-on-it)). If you really want a button, place the button inside the textfield like [here](https://stackoverflow.com/questions/38846087/make-button-inside-textfield-in-fxml) (not in FXML of course).

**Comment by madoar** [comment]
I'm not sure we want to automatically clear it, when the user clicks it. Maybe he just wants to add a missing letter?

**Comment by plata** [comment]
Ok. Then we should go for the button inside the textfield. Probably best to create a SearchBox class for that. The way how to do it is described pretty clearly in the link for FXML I posted above (Textfield and Button inside an AnchorPane).

**Comment by madoar** [comment]
I can do that.
Just to get a better understanding of what we want:
We're thinking about creating a class containing or extending an AnchorPane called SearchBox.
This class, or its AnchorPane, contains the search-Textfield and a Button that clears the Textfield after pressing it.

What is still open is the design of the "clear"-Button. Do we want to show a simple "x" or "&times;", without any background color or other style-changes?

**Comment by plata** [comment]
Either extend the AnchorPane or (if that's possible) the textfield directly. If SearchBox extends AnchorPane, we need to think about the change listener which triggers the search as you type. Maybe it would make sense to have a Consumer<String> in the SearchBox which can be set from outside and is triggered when the text in the textfield changes.

Regarding the design of the button: I suggest to use edit-clear.png from the Faenza icon theme (Faenza icons are used for the default theme).

**Comment by madoar** [comment]
Can you give me a link to the Faenza Icon Theme?
I can't find a working link, because it seems to be hosted on google code, which is not available anymore.

**Comment by plata** [comment]
Should be this one: <https://www.gnome-look.org/content/show.php/Faenza?content=128143>

**Comment by madoar** [comment]
Hmm, can I only download it via the PPA? The two links under files are dead, because they link to google code.

**Comment by plata** [comment]
For me, one of the links is working: <https://code.google.com/archive/p/faenza-icon-theme/downloads>

**Comment by madoar** [comment]
Ok, the page seems to need javascript to show the contents, otherwise you get a cryptic message.

**Comment by madoar** [comment]
The "clear" button has been implemented in PR #646.
