### ISSUE TITLE
Long waiting time until Applications in the "Apps" tab appear

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#650]
Currently it often takes a long time for me until the loading symbol in the center of the "Apps" tab disappears and the applications appear.

As far as I understand the current process, the content of the "Apps" tab is currently generated by searching the content of the github script repositories and local application sources.
Because I've added no custom application sources (repositories) to my installation, I guess the problem will be somewhere in the communication with the git-repositories.

**Comment by plata** [comment]
Do you know where the problem is caused? As you said correctly, it fetches GitHub by default so we need to know if there's something wrong in the code or e.g. simply your Internet connection is slow.

**Comment by madoar** [comment]
It shouldn't be my connection (100 Mbit/s connection).
I have this phenomenon every time I start POL 5. Is it possible, that the repositories are cloned every startup?

**Comment by plata** [comment]
Just had the same idea. Yes, I think so (need to verify in the code). There is a caching mechanism but it's only per session.

**Comment by madoar** [comment]
Yes I think so too. 
While we are at it, we should check if some modifications were done to the local clone. 
If such modifications were done it should either override the local changes or don't update to local repository. Maybe we can set this behavior in the Repositories Settings?

**Comment by plata** [comment]
I think we should not mix a user checkout with the GitApplicationsSource checkout. So I would just overwrite any local changes.

**Comment by plata** [comment]
Probably also better to use JGit instead of ProcessBuilder.

**Comment by madoar** [comment]
That's ok for me we should just document it. 
Maybe it would be best if we document the whole process around the git script repositories in POL 5, while working on this issue?

**Comment by plata** [comment]
Yes. The only quesion: where? Do we want to have this kind of documentation in the wiki?

**Comment by madoar** [comment]
I would do an approach like they do for [angular-cli](https://github.com/angular/angular-cli).
For angular-cli they have the documentation in their main repository which enables them to use pull requests for docu updates. 
In regular intervals they update the wiki with the newest version from the main repo.

**Comment by madoar** [comment]
How exactly does POL 5 interact with Git?

**Comment by plata** [comment]
Git is just one possible ApplicationsSource. If you specify one GitApplicationsSource in your properties, it will clone the given repository and fetch the available scripts from it. @qparis wants to replace it by a WebApplicationsSource by default for the released version.

**Comment by madoar** [comment]
So the whole communication with git is done in GitApplicationsSource where you're using the ProcessBuilder to run the local git installation (on your os) to clone the git application repositories?
If this is the case, what happens if you don't have a local git installation?

**Comment by plata** [comment]
Hopefully, git is listed as dependency for the package...

**Comment by madoar** [comment]
If we're using git only in the GitApplicationsSource, I should try to replace it with JGit, which should remove this dependency to a local git installation. 
What exactly should WebApplicationsSource do in the future? Is it only going to be an Interface, that is implemented by GitApplicationsSource for example?

**Comment by plata** [comment]
The plan is to have the scripts stored on some web server.

**Comment by madoar** [comment]
What's the benefit of that, compared to the current solution?

**Comment by plata** [comment]
@qparis said that he doesn't like git in a productive software. I wouldn't really care to be honest.

**Comment by plata** [comment]
Keep in mind that we can have multiple GitApplicationsSource, so we need a unique name for each checkout. Maybe something like:
```Java
final File gitDir = new File(cacheDirectory + "/git" + gitRepositoryURL.hashCode());
```

**Comment by madoar** [comment]
The question is how are the scripts updated in the productive software, with git, especially github, it's quite simple.

How are the names currently generated?

**Comment by plata** [comment]
It creates a tmp directory with `Files.createTempDirectory`. I'm not sure how that works internally (if there is any mechanism to handle this).

**Comment by plata** [comment]
For the wiki: I don't really like the idea to have the wiki twice an pollute the code with this. We should not get too many wiki changes from people without wiki access. I hope we can handle those through issues. People who contribute more often should be able to write to the wiki directly. However, I cannot decide that (you would have to ask @qparis).

**Comment by madoar** [comment]
Ok, I've just added a pull request for this, see #652. It would be nice if you could take a look at it and tell me a good final local destination for the cloned repositories.

In addition it seems like the application sources are loaded one at a time. It would be good for the initial clone performance of git repositories if they could be fetched in parallel, but I couldn't find where the repositories are fetched.

**Comment by plata** [comment]
Have a look at `MultipleApplicationsSource`.

**Comment by madoar** [comment]
In the catch clauses of the new JGit implementation, it may be needed to delete the repository folder, in case they couldn't be opened. Especially in case of an RepositoryNotFoundException, which can mean that the folder is not a repository. What do you think?

**Comment by madoar** [comment]
Ok, I just took a look at `MultipleApplicationsSource`. MultipleApplicationsSource seems to implement a linked list approach. 
This approach ensures, that every script is only loaded once, by comparing the scripts with the same name from two different application sources, where it takes the script from the first (left) application source.
I'm not sure if we really want this behavior long term, because it may be good to support multiple versions of a script, like a stable and a development version, see also #656. 

To fetch multiple application sources at the same time we would need to rewrite `MultipleApplicationsSource`. In addition this could make the merge-process harder, if we want to stay with the approach of only adding one script with the same name.
What do you think?

**Comment by qparis** [comment]
I definitely think that we should have only one script with the same name. The simpler, the easier, the better. 

The idea behind this implementation is to:
- be able to provide scripts integrated in POL (ClassPathApplicationsSource)
- be able to send newest version of these scripts without updated POL (GitApplicationsSource so far, but we are also going to create a RESTApplicationSource)
- let the user overide the remote scripts with a DirectoryApplicationSource

**Comment by madoar** [comment]
Does this mean, that we're going to reduce the application sources to ClassPathApplicationsSource, RESTApplicationSource and DirectoryApplicationSource and that we'll delete the other types (like GitApplicationsSource) at a later time? Or will it still be possible to add other application sources via the Repositories view in the "Settings" tab?

**Comment by qparis** [comment]
It will of course be possible to add them in the settings tab

**Comment by madoar** [comment]
Nice, this makes the development of new scripts easier later, if you can just add your own git repository to POL 5.
Should I rewrite MultipleApplicationsSource, to load the application sources in parallel, and still take the script from the earliest application source (in the list), that contains a script with the name?
This would essentially mean that we don't use the TeeApplicationSource in MultipleApplicationsSource to do the work.

**Comment by qparis** [comment]
If it greatly improves the performance, then you can go ahead yep

**Comment by plata** [comment]
We should be clear about the priority of the ApplicationsSources and document this (e.g. following the order in which they are specified).

**Comment by madoar** [comment]
I've added all still open things from this Issue to #663.
