### ISSUE TITLE
Slow performance of the search function in the "Apps" tab

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#651]
If you're adding a search keyword in the "Apps" tab, after all applications are loaded (see #650) the input isn't added fluently, often it seems stuttering to stutter when inputting or deleting something from the search-field.

**Comment by plata** [comment]
Can you track down the place (in the code) where this happens? It uses a callback for the fetching and `Platform.runLater` in ViewApps#populate to avoid this.

**Comment by madoar** [comment]
Ok, I've taken a look at this problem.
In my eyes the Platform.runLater is kind of useless in this case, because populate is called after the filter stuff has been completed. My guess is, that the problem is rooted in the action, that is performed when something is entered in the search-textfield.
The listener for the textfield is bound in line 150 in `ViewApps.java`:

```java
        searchBar.textProperty().addListener(obs->{
            String filter = searchBar.getText().toLowerCase();
            currentFilter.clear();
            if(filter != null && filter.length() >= 3) {
                currentFilter.add(new AppsSearchFilter(filter));
            }
            onApplyFilter.accept(currentFilter);
        });
```

onApplyFilter is set in line 48 in `AppsController.java`:

```java
        this.view.setOnApplyFilter(filter -> {
            appsSource.setFilter(filter);
            appsSource.fetchInstallableApplications(
                    this.view::populate,
                    e -> this.view.showFailure()
            );
        });
```

My guess is that everything together, before populate is called, needs a few moments to finish, and because pressed key adds or removes a character to the textProperty of the searchBar, the listener is called quite often. But because every call takes a while, it needs a visible amount of time until the last entered character has been processed by the filter method.

**Comment by plata** [comment]
Maybe we should use a FilteredList to avoid fetching all the time. Additionally, we could delay the search a bit (so the search only starts after you stopped typing).

**Comment by madoar** [comment]
What could maybe help too is:

```java
searchBar.textProperty().addListener(obs -> Platform.runLater(() -> {
            String filter = searchBar.getText().toLowerCase();
            currentFilter.clear();
            if(filter != null && filter.length() >= 3) {
                currentFilter.add(new AppsSearchFilter(filter));
            }
            onApplyFilter.accept(currentFilter);
        }));
```

**Comment by plata** [comment]
I don't think it makes sense to do this. The only thing which could take some time is the fetch once the filter is applied and this is using BackgroundApplicationsSource already.
