### ISSUE TITLE
Log Repository information

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#659]
Sometimes, especially when writing logging code or debugging output, it's really useful to have a meaningful name for an `ApplicationSource`. Therefore I suggest that we add a getter-method declaration to `ApplicationsSource` called `getName()` that has the task to return the name of the application source.

**Comment by plata** [comment]
What about putting this in `toString`?

**Comment by madoar** [comment]
Hmm, under a `toString` method I imagine more than the simple printout of the name of the application source (which for a git application source is its url). In addition to the name, I would also print information such as the number of categories and scripts inside it, in the `toString` method.

**Comment by plata** [comment]
You're right. Seems a bit strange to me to have a function which returns the name of the class for debugging, but if you think it's useful why not.

**Comment by madoar** [comment]
Oh `getName` shouldn't (only) return the name of the class, because this wouldn't be enough to differentiate between two application sources of the same type, like two `GitApplicationsSource`s.
For git application sources I would return the repository url, and for local application sources I would return the path to the folder, with `getName`.

**Comment by plata** [comment]
This sounds almost like `toString` then^^

**Comment by plata** [comment]
@madoar what shall we do about this? Is it still valid?

**Comment by madoar** [comment]
I'm not sure, I think we need this for debugging purposes, but because we've always had more important issues, I couldn't address this yet.

**Comment by plata** [comment]
Ok. How about renaming this issue to: "Log used repositories" or something like that?

**Comment by plata** [comment]
@madoar we have a log output for the used repositories by now. Apart from this, it seems like nobody needed more functionality here in the last months. Therefore I would suggest to close this.

**Comment by madoar** [comment]
It seems like you're right.
The point of this issue was to do some fundamental work in regards to making the merge process of multiple repositories better debugable, i.e. which repository was merged in which order.
Every time I look at the merging code, I think it contains some kind of error...

**Comment by plata** [comment]
Ok. I'll close it for now. If we ever encounter a problem there, we can still improve the logs.
