### ISSUE TITLE
Leftover things from other issues

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#663]
In this Issue I'll add all things that are left over from other Issues:  
- [X] Remove the cache from `GitRepository`. For caching purposes a `CachedRepository` should be used.
- [X] Document all types of `Repository`s that exist in POL 5 in the wiki. 
- [X] Document the whole process needed to fetch a `GitRepository` in the wiki.
- [X] Document the process in which the scripts from the applications sources are loaded in the wiki. This includes a remark about the priority of the application sources that is specified through their order
- [X] Document the styling information about the new `SearchBox` gui-component in the wiki.
- [ ] Implement functionality in `GitRepository` that is performed, when the found directory for the git repository is no git repository (i.e. a `RepositoryNotFoundException` is thrown).

**Comment by plata** [comment]
I created a new [wiki page](https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository). However, I think we should not put detailed source code documentation (e.g. how the `GitRepository` works) there. This should be done in JavaDoc directly in the code.

What do you have in mind for the last point?

**Comment by madoar** [comment]
About the documentation for the `GitRepository`:
I'm not talking about source code here. What I had in mind was to describe the process as an enumeration, that contains in words what is done in which order. Especially, such information, that it automatically calls git pull if the folder already exists, otherwise the used could come to the conclusion that the local git repository is never updated, which is false.

About the last point:
If the folder for the git repository exists, but it somehow defect (i.e. a `RepositoryNotFoundException` is thrown) I would suggest to delete the folder and clone the git repository again.

**Comment by plata** [comment]
Updated the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository). Is it ok like this? Otherwise please tell me what I should write there.

**Comment by madoar** [comment]
Sounds good, what I find a bit vague, is the part containing `the most right entry`, here I would use the latest entry or something similar.

**Comment by plata** [comment]
Done.

**Comment by plata** [comment]
For the second task: Do you want more description than there is currently in the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository)? If so, what shall I write there?

**Comment by plata** [comment]
Is the `SearchBox` theme description in the [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Themes#left) sufficient?

**Comment by plata** [comment]
For the last task: Currently we have a log output. I think that should be sufficient (at least for now).

**Comment by madoar** [comment]
I've just added additional information about the repositories (see here: https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository) 
What do you think?

**Comment by plata** [comment]
I like it. Great that you have the rights to edit it directly now. I'm just trying to get rid of all those old issues.

**Comment by madoar** [comment]
For the last point I think we need a way to "reset" the repositories.
If the repository is corrupt, what should the user do, should should he find out?

**Comment by plata** [comment]
We need a pop-up when something goes wrong while fetching the repository. This pop-up should then show the problem. Could be several things:
* no Internet connection
* folder does not exist
* folder is not a git repository 
* ...

For me, this should be a completely new issue.
