### ISSUE TITLE
Resolving errors with javafx css stylesheets

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#671]
When changing themes and moving between different tabs and screens I sometimes get messages such as:
> WARNUNG: Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-fill' from rule '*.text' in stylesheet file:/home/marc/Dokumente/Play%20on%20Linux/POL-POM-5/phoenicis-javafx/target/classes/org/phoenicis/javafx/themes/breezeDark/main.css

> WARNUNG: Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell:focused:filled:selected' in stylesheet file:/home/marc/Dokumente/Play%20on%20Linux/POL-POM-5/phoenicis-javafx/target/classes/org/phoenicis/javafx/themes/breezeDark/main.css

> WARNUNG: Could not resolve '-fx-accent' while resolving lookups for '-fx-background-color' from rule '*.combo-box-popup>*.list-view>*.virtual-flow>*.clipped-container>*.sheet>*.list-cell:hover:filled:selected' in stylesheet jar:file:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss

**Comment by plata** [comment]
Maybe it does not use the root to resolve the lookups. Could you try this:
```CSS
* {
   -fx-bright: #eff0f1;
}

.text {
    -fx-fill: -fx-bright;
}
```

**Comment by madoar** [comment]
Ok I've just renamed .root to * in the css files for PR #670.
