### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by feanor12** [PlayOnLinux/POL-POM-5#673]
I tried to build 0a3edfe694e1d4115e22ba97ea3805d9124faa93 and I get an error, but 8cfc7851e844e62c82a7f447ba583d9a02dfeed5 works.

**Comment by feanor12** [comment]
http://pastebin.com/BfYL1zRg

**Comment by plata** [comment]
The same here. @madoar can you check this (it's most probably caused by  #668)?

**Comment by plata** [comment]
Could be: <https://github.com/TestFX/TestFX/issues/364>

**Comment by madoar** [comment]
@feanor12 which JDK are you using? OpenJDK or OracleJDK?
Can you test the linked project in https://github.com/TestFX/TestFX/issues/364 (https://github.com/Maxoudela/MonocleTest)?
In addition can you try to locally set a newer version for `openjfx-monocle` in the pom.xml in the javafx project, because I've set a quite old one?

**Comment by feanor12** [comment]
java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by feanor12** [comment]
I tried `<version>8u76-b04</version>`, but it still get an error.

**Comment by feanor12** [comment]
If I run `mvn package` or `mvn test `on https://github.com/Maxoudela/MonocleTest I get an error.
http://pastebin.com/vTzVDr0q
http://pastebin.com/wiWrdf2U

**Comment by feanor12** [comment]
If I change textfx to 4.0.6-alpha (local build of TestFX master) I can build POL5

**Comment by madoar** [comment]
Ok, this means it's a combination of OpenJDK and testfx 4.0.5-alpha.
I suggest we simply comment the test out and comment it back in when testfx 4.0.6-alpha is officially released. What do you think?

**Comment by feanor12** [comment]
Sounds like a solution. I don't know if it's possible in maven to add the git repository as dependency and build a snapshot.

**Comment by madoar** [comment]
It's not possible to directly add a git repository as a dependency to maven.
But what's possible is to use a service, that builds the contents in the repository for you and distributes the result via maven.
For details look [here](http://stackoverflow.com/questions/20161602/loading-maven-dependencies-from-github) and [here](https://jitpack.io/#maven)

But this seems more or less like a hack.

**Comment by lans98** [comment]
How can I build from 8cfc785?

**Comment by madoar** [comment]
You can build POL 5 in the terminal via `mvn clean package`.

**Comment by plata** [comment]
@madoar could you comment the test and add an issue to uncomment it when 4.0.6-alpha is available?

**Comment by madoar** [comment]
I'll do that. I'll also move the jvm parameters from the surefire plugin to the test itself.
I'm not sure where we want to set them in the end. I think that if we set them in the test we need to set them for every test class. What do you think?

**Comment by plata** [comment]
We should not have to set it for every single test. If we could set it in one place for all TestFX tests, we should do that. Otherwise just for all tests.

**Comment by feanor12** [comment]
@lans98 
```
git clone https://github.com/PlayOnLinux/POL-POM-5.git
cd POL-POM-5 
git checkout 8cfc785
mvn clean package
```

**Comment by madoar** [comment]
I don't know if this is possible with JUnit.
One way would be to use the surefire plugin. I would prefer to do it in the source code via 
```java
static {
        System.setProperty("testfx.robot", "glass");
        System.setProperty("testfx.headless", "true");
        System.setProperty("prism.order", "sw");
        System.setProperty("prism.text", "t2k");
}
```
I don't know where to add this code, that it gets applied to all tests. Any ideas?

**Comment by feanor12** [comment]
4.0.6-alpha was released and should be available at maven central in a few days.

**Comment by feanor12** [comment]
https://search.maven.org/#search|ga|1|org.testfx
4.0.6-alpha is available.
