### ISSUE TITLE
Add multiple JDKs to Jenkins

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#674]
As seen #673 it seems so make a difference which JDK you use to build POL 5. Therefore I would suggest to test POL 5 with multiple JDKs with Jenkins.
In addition I think it would be nice, if Pull Requests are tested by Jenkins by default.

**Comment by plata** [comment]
I can understand why Jenkins does not test pull request for non-collaborators by default. Otherwise someone could just spam it. In my opinion people who commit often (like you now) should just be added as collaborators after some time.

**Comment by madoar** [comment]
You are right, it isn't the best idea to test all PRs. But I think Jenkins should test with multiple JDKs, at least OracleJDK and OpenJDK.

**Comment by qparis** [comment]
Agreed, but it is a bit more complicated. 

Would OpenJDK be sufficient?

**Comment by madoar** [comment]
@qparis I think only OpenJDK won't suffice, but OpenJDK an OracleJDK should suffice.
