### ISSUE TITLE
Use variables to defines colors in the themes

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#675]
```CSS
* {
   -fx-bright: #eff0f1;
}

.text {
    -fx-fill: -fx-bright;
}
```

**Comment by madoar** [comment]
If you want to address the need to rename `.root` to `*` with this issue, I guess this is done with #670.

**Comment by plata** [comment]
No. I really want names for the colors (like you did in #677 with LESS).
