### ISSUE TITLE
Adjust Ubuntu theme?

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#682]
I don't think the box round the header tabs when you click on them is necessary or looks nice.
Opinion-based, but I guess most theming stuff is.
![screenshot from 2017-03-26 15-25-02](https://cloud.githubusercontent.com/assets/3178485/24332096/81604226-1238-11e7-9e9f-b33984beabbb.png)

**Comment by plata** [comment]
You are right. It shouldn't look like this.
