### ISSUE TITLE
Icons installed windows software in the system menu

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#687]
Maybe add question "Do You want add shortcut in system menu?" after installation.
What do You think about this idea?

**Comment by madoar** [comment]
In addition to this I'm also not sure if short cuts to the system menu are currently fully removed when the container gets deleted.

**Comment by plata** [comment]
If you want to try, here's what needs to be done:
- add boolean `desktopShortcut` to Functions/Shortcuts/Wine/script.js and pass it in `createShortcut`
- enhance `ShortcutManager#createShortcut` with the new parameter
- add an additional menu step to the quick scripts in Functions/QuickScript to query the user`s selection

**Comment by pyroxar** [comment]
CrossOvers support shortcut for installed application in system menu.

**Comment by plata** [comment]
As we maintain our own .desktop files, I think it would make sense to disable the shortcuts created by winemenubuilder in general. See [Wine.hq FAQ](https://wiki.winehq.org/FAQ#How_can_I_prevent_Wine_from_changing_the_filetype_associations_on_my_system_or_adding_unwanted_menu_entries.2Fdesktop_links.3F) for how to do this (we would implement it in JS Wine). This would also assure that those shortcuts do not remain in the menu after the app has been uninstalled.

@madoar what do you think about this approach?

**Comment by madoar** [comment]
If I understand you correctly you suggest to handle the shortcut management in POL 5 only and don't use wine features for this? Therefore we need to supply functionality to create, maintain and delete shortcuts?

If my understanding is correctly I think this is a good approach.

**Comment by plata** [comment]
Yes. As we maintain our own shortcuts anyways, I think this is the simplest solution.
