### ISSUE TITLE
Error when adding a local repository, whose path contains a space character

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#696]
Currently it leads to a POL 5 software freeze, and a corrupted `config.properties` file, if you add a `LocalRepository`, whose directory path contains a space (" ") character. 
This happens, because the Java `URI` class can't handle space characters.

**Comment by qparis** [comment]
Even with %20?

**Comment by madoar** [comment]
When you use `%20` (I tried) the URI won't throw an exception, but the file object created in `LocalRepository` line 62 will return `false` if you call `repositoryDirectoryFile.exists()`, which suggests, that the File object doesn't parse `%20` as a space character.

**Comment by plata** [comment]
Similar to #639?

**Comment by madoar** [comment]
Yes, I think so.

**Comment by plata** [comment]
So same fix possible?

**Comment by madoar** [comment]
Basically yes, but we would also need to change all paths/urls, that are currently passed to the repositories, to URIs.

**Comment by plata** [comment]
Do you see a better solution?

**Comment by madoar** [comment]
No, I'm just too lazy to do that now :D

**Comment by madoar** [comment]
Ok, I've just experimented a bit about this. My results are, that `URI`s are ugly. 
If we decide to use URIs internally, we need to encode **every** hyperlink, path etc. 
This means, that `git+https://github.com/madoar/Scripts` becomes `git%2Bhttps%3A%2F%2Fgithub.com%2Fmadoar%2FScripts`.
This alone wouldn't be too bad, but in combination, that we want to display some URLs/URIs to the user either as direct output or for debugging purposes, this looks quite bad.

I believe it would be much better, to simply don't use `URI`s and work only with Strings, because every class we have that uses links/paths receives them as Strings and uses them as Strings (e.g. GitRepository, LocalRepository and ClasspathRepository).
What do you think?

**Comment by plata** [comment]
So we cannot read the string from the properties convert it to URI and show it in a nice format again? I don't have a problem using only Strings but on the other hand it feels kinda weird to do that if there is a special class to store URIs.

**Comment by madoar** [comment]
The problem in my eyes is, that Java doesn't provide a way to create encoded `URI` objects from a `String`. To do this you would need to use support classes, that, when you use the ones provided by Java itself, take a String and produce an encoded version of the String. Then you can take this encoded String and pass it to the URI constructor. 

This leads to the URI object not knowing how the string looked before the encoding.
I'm not sure if there is an elegant (and short) way to print an URI in a nice format.

**Comment by plata** [comment]
I can't believe we're the only ones with this issue :P

**Comment by madoar** [comment]
Do you want to give it a shot?^^

**Comment by plata** [comment]
I did some research but also could not find a nice solution until now...

**Comment by madoar** [comment]
What seems to be a possibility is to use the classes `URLEncode` and `URLDecoder`, which can encode/decode a `String`, but I'm not sure if we want to do this.
