### ISSUE TITLE
Strange Java Error

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#700]
When testing a PR I tumbled over the appended error message.
Have you seen such an error before?

[hs_err_pid10106.log](https://github.com/PlayOnLinux/POL-POM-5/files/919250/hs_err_pid10106.txt)

**Comment by plata** [comment]
Segmentation fault in the JRE itself? Never seen such a thing. And I don't think it's related to our program in any way.

**Comment by qparis** [comment]
Why do we have some GtkApplication classes here?

**Comment by madoar** [comment]
I don't know. Maybe Oracle JavaFx uses it internally?

**Comment by qparis** [comment]
Should be fixed

**Comment by plata** [comment]
@madoar can this be closed?
