### ISSUE TITLE
Improved merge-process

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#705]
I've some ideas how to improve our merge process, so that we don't accidentally break our master branch.

First I would introduce a new `development` or `develop` branch, which has the function of our current master branch.
Whenever we have a pull request, which looks mergeable we merge it in the development branch.
Jenkins in addition should then be configured to automatically test all commits/merges made to the development branch.
Lastly we can then savely merge changes from the development branch to the master branch.

What do you think about this?

**Comment by plata** [comment]
This would require that someone tests the develop branch. So in the end you just shift this from master to develop which does not make a lot of sense in my opinion because the users should use the releases anyways.

**Comment by madoar** [comment]
Why does someone need to test the develop branch? 
I'm suggesting to always automatically test it with jenkins.

**Comment by qparis** [comment]
I agree with plata, having a dev branch would not change anything because its commits would also have to be tested.

The current process work great (when Jenkins is not down, of course)
