### ISSUE TITLE
Adding a StyleManager/CSSManager

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#711]
I don't like our current way of interacting with the stylesheets.
Ideally I would like to integrate the handling/interacting in the `ThemeManager` or a new class called `StyleManager` or `CSSManager`.
This class should encapsulate the interaction with stylesheets via an `set()` method, which takes two arguments:

- The first argument is an enum, which tells the method what type of stylesheet you want to set. This value can `DEFAULT_THEME`, `USED_THEME`, `CATEGORY_ICON_THEME` and maybe some other values we'll need.
Depending on the given enum value the method then decides which value inside the stylesheet-list it needs to change.
- The second argument is a File object. This file object is the new stylesheet to be set.

For context details see #681.

What do you think?

**Comment by plata** [comment]
Makes sense. It should be done in `ThemeManager`. 

We should first think about the themes we need. I see different levels for this:
- DPI: defines only sizes depending on the screen resolution
- look'n'feel: default, Breeze Dark, Unity etc.
- icons
    - app category: default/themed
    - engine category: default/themed

**Comment by madoar** [comment]
How would you set the DPI?
Only by changing the icons, or is there more to be done?
Another question about the DPI that appears to me is, do we then need to have multiple icon sets for each look'n'feel theme? (One in high DPI, another one in low?)

**Comment by plata** [comment]
Currently, there's an (unfinished) HiDpi theme which is basically the default theme with everything enlarged. Therefore you cannot use e.g. the Unity theme on a HiDpi screen. I think it would be better to split the style and the sizes. For example, the Full HD size of a button could be 60x20 and the HiDpi size 120x40.

We do not need different icon sets because they are resized. Unfortunately, that's not possible if you set the button graphic in CSS so we had to set the background image (so the SearchBox has to use the same approach).

**Comment by madoar** [comment]
About the SearchBox:
I have nothing against changing `-fx-graphic` to `-fx-background-image`. The reason I didn't use `-fx-background-image` was because you need to use some other css tags too if you want the image to be centered and not repeated.
In addition we need to set good insets for the searchfield clear button. 

About the HiDPI themes:
Is the HiDPI theme only about changing the size of the icons/elements and is this done uniformly (all elements are shown with 300% their width, height etc.) or is there more to it?
If we simply need to change the sizes of the components, then we can create one HiDPI css file, which contains the size information for **all** HiDPI themes, the same we can do for **all** low DPI versions.
This would prevent the need to create an individual HiDPI and low DPI version for each theme.

**Comment by qparis** [comment]
Side note: The CSS should be a URI, not a file :-)

**Comment by plata** [comment]
> then we can create one HiDPI css file, which contains the size information for all HiDPI themes, the same we can do for all low DPI versions.
This would prevent the need to create an individual HiDPI and low DPI version for each theme.

That's exactly what I have in mind.

**Comment by madoar** [comment]
After we've removed the HiDPI theme in the settings and replaced it by a scaling option, is it still needed to add a way to set the HiDPI state in the `ThemeManager`?

**Comment by plata** [comment]
No.
