### ISSUE TITLE
Investigate why the test "testListPermutation" fails on Jenkins

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#712]
I don't think it's healthy to simply ignore the test `testListPermutation` in the JUnit class `MappedListTests` long term.
Therefore we should investigate why this test fails on Jenkins.
First I would like to know if this test fails only for Jenkins?
At least for @plata and me the test seems to work as intended locally.

**Comment by madoar** [comment]
Ok, after seeing the tests for #730 failing again because of the same reason, I've searched a bit on the internet for a reason and found this:
http://stackoverflow.com/questions/29854327/javafx-observableliststring-sorted-vs-sortedcomparator-stringnaturalorder

@plata, @qparis what Java version is Jenkins using?

**Comment by plata** [comment]
From the [logs](http://www.playonlinux.org:8080/job/POL-POM-5_PullRequest/713/consoleFull): `/home/jenkins/tools/hudson.model.JDK/Oracle_JDK_1.8`

**Comment by madoar** [comment]
Hmm, this still doesn't tell us which version (update) was used.

**Comment by plata** [comment]
If it's not visible in the output, I can't tell. @qparis needs to look at the machine directly, I guess.
