### ISSUE TITLE
Use Tri-state Checkboxes

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#722]
JavaFX Checkboxes have the ability to support three states: true, false and indeterminate.
I think we should use this in POL 5 to support the option "undecided".
As an example I would suggest using a single tri-state checkbox for the engines tab to give the user the choice to filter for installed, uninstalled and both engines.

What do you think?

**Comment by plata** [comment]
I'm not really sure the meaning is obvious to the user.

**Comment by plata** [comment]
@madoar is this still valid?

**Comment by madoar** [comment]
I would like to try this in combination with #731, but I didn't find the time yet to try this.

**Comment by plata** [comment]
Ok. Just looking through the issues again to see what can be closed or not.
