### ISSUE TITLE
Unable to add executable to Library from existing container

### ISSUE THREAD

**Issue by CreshZmine** [PlayOnLinux/POL-POM-5#727]
When a software with Local Installer complete his setup there is no way to create a link to them in the library

**Comment by plata** [comment]
Can you describe the issue in more detail?

What should happen is that you see the window below which lets you select an executable. A shortcut for this executable will then be added to your library.
![select](https://cloud.githubusercontent.com/assets/3973260/25395060/25f1a1c2-29e0-11e7-9623-73c2cad02296.png)

**Comment by CreshZmine** [comment]
My installation complete withount error but I have no links in Library and I can't create it manually like on POL4.

**Comment by plata** [comment]
Did you see the menu step with the selection?

**Comment by CreshZmine** [comment]
No. I suppose this is the issue.

**Comment by plata** [comment]
Any output on the command line (in case you started from command line)?

**Comment by CreshZmine** [comment]
Now It's asking after the setup for another install file and I can't skip. I can only cancel aborting all the process.

![image](https://cloud.githubusercontent.com/assets/9625583/25396344/88e8c3f6-29e4-11e7-8f8d-c1933a718c4e.png)

**Comment by plata** [comment]
That's correct now. You have to select the executable which you want as shortcut in your library.

**Comment by CreshZmine** [comment]
Ah ok. I'll try. I suppose that this section need some more info. But I can't create another shortcut without making a new install?

**Comment by plata** [comment]
The text is set in [InstallerScript](https://github.com/PlayOnLinux/Scripts/blob/master/Functions/QuickScript/InstallerScript/script.js) (l. 88). You're welcome to provide a pull request which improves this.

You can only create one shortcut. The custom installer is a kind of last resort if there is no installation script. Usually you should use an installation script, therefore the custom installer is rather simple. What are you trying to achieve?

**Comment by CreshZmine** [comment]
Thanks for info. I'll try to do my best.
I use PlayOnLinux to test apps with various Wine version so, sometimes. if something crash with a custom shotcut to a particular app in a particular container could recover the status. But thanks for support.

**Comment by plata** [comment]
What you can do is change the shortcut manually in `.Phoenicis/shortcuts/`. If you think we should have the possibility to add a new shortcut from the GUI, feel free to open a new issue for this. Even better of course: provide a pull request which supplies that functionality.

**Comment by CreshZmine** [comment]
I'll study the code and provide what I can/I'm able to do. Thanks for all.

**Comment by plata** [comment]
You're welcome.

Can we close this issue?

**Comment by CreshZmine** [comment]
Yes. Thanks.
