### ISSUE TITLE
Implement functionality for the filter checkboxes in the "Apps" tab

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#731]
Currently we have 3 checkboxes in the sidebar of the "Apps" tab, that do absolutely nothing.
We should add some functionality to them.

**Comment by plata** [comment]
Filter should be implemented like in #723. The checkboxes relate to fields in `ScriptDTO`. 
As the "Apps" tab shows applications and not scripts, I'm not quite sure how the behavior shall be. For example, you could imagine a game which has two scripts: "real" game, demo. While you need to pay for the game, the demo is free.

**Comment by madoar** [comment]
If this is the case, then I would suggest doing this in two steps:

1. First filter the applications shown in the `MiniatureListWidget` inside the "Apps" tab to only show the applications containing **at least one** `ScriptDTO` that fulfills the selected filter criteria
2. After the user clicked on an application in the `MiniatureListWidget` inside the "Apps" tab filter the `ScriptDTO`s belonging to the selected application, so that only the `ScriptDTO`s are shown that fulfill the selected filter criteria

This approach first reduces the number of shown applications and afterwards the number of relevant scripts.

**Comment by plata** [comment]
Yes, that's probably the best solution. 

I just don't agree with 

> so that only the ScriptDTOs are shown that fulfill the selected filter criteria

If "Testing" is selected, we should show all scripts (testing + stable).

Moreover, I would suggest to replace "Commercial" by "Free" as the majority of applications (especially games) will be commercial.
