### ISSUE TITLE
"Back" button

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#733]
Currently in the "Apps" and "Engines" tabs there is no defined way, how to return to the `MiniatureListWidget` from a miniature page.
For example, if you select an engine in the engines tab, you only see two buttons: "Install" and "Delete", but no button to return to the engines selection list.

Do you have an idea how we could/should handle the "move to the last window"/"go back" functionality?

**Comment by plata** [comment]
I think there are mainly two options:
* a "Back" button in a bar at the top
* something like in Plasma Discover where a new column is opened to show the detailed information (see <https://userbase.kde.org/Discover>)

**Comment by madoar** [comment]
I think option one would be the easiest to implement, but option two would look better. 
For option two we could replace the SearchBar with a "Back" button whenever a back button is needed.
We can do this, because a back button is normally needed, when a SearchBar isn't.
What do you think?

**Comment by plata** [comment]
I guess we have to try it to see how usable it is. I hope that I find some time to implement something this weekend.

**Comment by plata** [comment]
Quick try of the second option:
![new column](https://cloud.githubusercontent.com/assets/3973260/25555345/4970739c-2ce4-11e7-9be6-2c02f40091d4.png)

@qparis @madoar What do you think?

**Comment by madoar** [comment]
Looks really nice. But I'm not sure how usable it is if you have a really small monitor or resolution.
In addition it may be better make a vertical divide.

I've just pushed a PR, that simply adds a "Back" button to the left side. The interesting part of my PR is, that it adds a navigation chronicle to the `MainWindowView` class that enables many layered back navigation, which we will eventually have if we use the engines install wizard to change the engine version of an existing container, see #625.

**Comment by plata** [comment]
Maybe we can have a combination of both. I don't think a horizontal divide is a better idea (everyone is using wide screens). The right part for apps could be a lot smaller.

**Comment by qparis** [comment]
I link it. Is the column always shown?

**Comment by plata** [comment]
It occurs when you click on a miniature. The miniature should be highlighted and probably there should also be a close button for the right column.

**Comment by madoar** [comment]
What would happen if we need a larger hierarchy of subwindows at a later time?
For example when we want to change the engine of a container:
> Container -> Engines List -> Selected Engine

**Comment by plata** [comment]
I don't think we should go from Containers to the Engines tab. We should rather use a small embedded wizard.

**Comment by madoar** [comment]
I'm not talking about navigating to the Engines tab. I would show a TabPane like inside the Engines tab, but not the engines tab itself. 
This would require three selections by the user:

1. Select the container, whose engine you want to change
2. Open the possible engines list (if the old engine was a wine engine we only show the wine engines)
3. Select the required new engine from the shown `MiniatureListWidget`

**Comment by plata** [comment]
How would you convey the idea that you are currently selecting a new engine for the specific container?

**Comment by madoar** [comment]
With your approach, by opening a third Panel in the SplitPane.
In my approach I would return step by step (from the selected new engine to the `MiniatureListWidget`, then from the `MiniatureListWidget` to the selected container).

**Comment by plata** [comment]
In this scenario, I think your approach makes more sense. I don't see that the new column should be used for something like this. The new column should only be used to show detailed information about a selected item. Therefore the engine selection for a container is quite a different use case.
However, you should consider that your implementation is really similar to a wizard. We must be careful that we do not end up with two different wizards in the same GUI.

**Comment by madoar** [comment]
You're right.
Another thing we shouldn't forget is that my engine changing case is an exception and not the rule.
In addition I like the columns too.
I think we should go with the `SplitPane` approach, but I would like to integrate the navigationChronicle structure from #735. If we replace the Stack by an ObservableList we can bind the this list to the content of the SplitPane.
What do you think?

**Comment by plata** [comment]
Actually, I used the `right` of the existing `BorderPane` and not a `SplitPane` (not really important, just to clarify).
I'm not quite sure if I understand your proposal correctly. Could you give an example how this would behave (from a user perspective)?

**Comment by madoar** [comment]
The interesting aspect of the navigationChronicle is that it contains all currently opened "windows".
So when you clicked on an application in the MiniatureListWidget it contains 2 items:

- The MiniatureListWidget
- The Panel containing the application details

If you're looking at the engines list it only contains a single item the TabPane.

The navigationChronicle is managed by the `MainWindowView` class:

- To add an item to it you need to call a method `navigateTo`
- To clear the list and then add an item, you need to call `clearChronicleNavigateTo`
- To remove an item you call `returnTo(int itemsToRemove)` to remove the last `itemsToRemove` items

If you bind the navigationChronicle list to the items of a SplitPane:
```java
Bindings.bindContent(splitPane.getItems(), navigationChronicle);
```
All currently opened items are automatically shown.
Does this answer your question?

**Comment by madoar** [comment]
If you want to make the items inside the SplitPane closeable, it should also be quite easy when you use a binding.
In this case you would use an additional MappedList which takes a list of items (`Node` objects in our case I guess) and wraps them inside another Panel, which adds a close button.
Then when we bind to the SplitPane, all shown items will automatically have a close button.

**Comment by plata** [comment]
I still don't really understand how this would be used to navigate. I will do a really basic PR to enable the split then you can go ahead.

**Comment by madoar** [comment]
The navigation is done by calling `navigateTo`, `clearChronicleNavigateTo` and `returnTo` inside the action listeners of the buttons. 
Because this is like it already works currently, you won't need to change it much :)

**Comment by plata** [comment]
I meant the behavior of the GUI.

**Comment by madoar** [comment]
It would work like it does for your current approach I think.
you would click on an application icon in the `MiniatureListWidget` and a second window is automatically opened/added in the SplitPane. This second window contains the `AppPanel` to the application you've selected.

**Comment by plata** [comment]
Superseded by and #737 and #759.
