### ISSUE TITLE
miniature list: select miniatures or simple list

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#736]
Allow to switch between a miniature list and a simple list (only Strings without icons).

**Comment by madoar** [comment]
How shall the user select, which view he wants to have?

**Comment by plata** [comment]
Maybe as global option in settings → UI or buttons like in a file browser
![buttons](https://cloud.githubusercontent.com/assets/3973260/25563095/9c859f70-2d94-11e7-8ba4-70dac7c34927.png)

**Comment by madoar** [comment]
I think the second one looks approach in your screenshot looks better.

**Comment by plata** [comment]
That's only GIMP. What concerns me a bit is that the icons are not directly related to the miniature view.

**Comment by madoar** [comment]
The problem when using a global option in the settings for this is, that I don't think a lot of users will find this option or understand what exactly it does by looking at the description.

**Comment by plata** [comment]
That's probably true.

**Comment by madoar** [comment]
@plata if you have nothing against it, I would like to have a go at this. 
What I would like to know before I start is, which buttons in the left bottom of the sidebar do we want to use? It seems like the Faenza icon set has 2 icons we could use, at least for the default design.
But I must say that I like the icons from your screenshot better. If you agree with them too can you share them here?

**Comment by plata** [comment]
Feel free to assign yourself. The icons in my screenshot are from Breeze Dark (actually from a screenshot I made of Dolphin). I'm not sure we should use them in the default theme. The style should match Faenza, so I would try those icons first.

**Comment by plata** [comment]
Should be:
* view-list-compact-symbolic.png
* view-list-details-symbolic.png
* view-list-icons-symbolic.png

**Comment by qparis** [comment]
Honestly I find the miniature list cleaner

**Comment by qparis** [comment]
I think you could take advantage of the list to display extra information

**Comment by qparis** [comment]
However, we should let the user chose want view he wants

**Comment by madoar** [comment]
@qparis what do you mean with miniature list? My "new" one or the old one?

This is only my first approach, where I'm testing how to set the width/height etc. properties.
Therefore you can't switch the view atm.
What additional information do you want to have shown?

**Comment by qparis** [comment]
The name of the container, or the engine could be displayed for instance

**Comment by madoar** [comment]
As far as I know these information are not available for the `ApplicationDTO` objects in the "Apps" tab?
I'll keep it in mind, when I add the new list to all tabs

**Comment by qparis** [comment]
This is correct. The idea is just ton leave less empty spaces.

You could also put the category of the app

**Comment by madoar** [comment]
The category is a good idea.
But I'm not sure how to prevent empty space, especially if the user has the ability to change the size of the POL 5 window, as shown in my last screenshot. 
There is only so much information to be shown...

**Comment by madoar** [comment]
In addition it's quite problematic if a list entry contains too much information, because we need to add a horizontal scrollbar then. This then makes the list hard to use, or even impossible to use, especially when the user has a small POL 5 window or a small monitor/resolution, see my earlier screenshots how much space is available inside the small list.

**Comment by plata** [comment]
I like it. Can we also have a version without images (that's what I had in mind originally)? Also I don't feel like the empty space is a problem. In my opinion, you would choose the list to save space so the 3. screenshot represents the looks much better than the last one. 
We can think about showing additional information like category, compatible for my OS, commercial etc. However, if we do this, we should handle it like a file browser: several columns and the possibility to select which information you want. This is totally out of scope for this issue.

**Comment by madoar** [comment]
@plata yes I've planned for 3 versions, the old miniature list widget, an icon list (see my screenshots) and a detailed list without icons.

**Comment by plata** [comment]
That's great! I think the implementation for this issue can really concentrate on the basics. As long as you can switch the views, it's sufficient for me. All the other improvements can be done later on.

**Comment by madoar** [comment]
Here a few more screenshots of how it looks currently:
![grafik](https://cloud.githubusercontent.com/assets/18488086/26054984/393053b6-396f-11e7-9700-1d0f1ba5c302.png)
![grafik](https://cloud.githubusercontent.com/assets/18488086/26054985/3b09c8de-396f-11e7-9d5a-4b55eab0aeec.png)
![grafik](https://cloud.githubusercontent.com/assets/18488086/26054990/3cfc824e-396f-11e7-8576-09fdc27824cd.png)
![grafik](https://cloud.githubusercontent.com/assets/18488086/26054992/3eeb1232-396f-11e7-8346-4dbdeebccb78.png)

Like you can see it's now possible to switch between the old miniature list (which is now renamed to icons list) and the new list which is called compact list.
The third list type is coming soon.

**Comment by plata** [comment]
:+1: 

The left alignment of the switch button doesn't seem to be right.

**Comment by plata** [comment]
Fixed by #797.

@madoar could you use keywords in the future so that the fixed issue is closed automatically (see <https://github.com/blog/1506-closing-issues-via-pull-requests>)?

**Comment by madoar** [comment]
I'm trying, but I didn't want to close this after my PRs were merged, because I thought that we need to improve the themes first to be more compatible with the new list widgets. Now that you did some PRs that targeted this goal we can close this.

**Comment by plata** [comment]
In those cases it would be better to create a new issue which specifically targets the left open topics.

**Comment by madoar** [comment]
Ok, I'll try to keep this in mind
