### ISSUE TITLE
decide on 4-level JS namespace

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#745]
see #622

A 4-level JS namespace would allow to clearly separate installable application scripts and the framework.

**Comment by madoar** [comment]
Are there any news on this?

**Comment by plata** [comment]
Not really. I still believe it makes sense to have all apps in one folder and the functions in another but I don't want to take any decision here without @qparis.

**Comment by qparis** [comment]
I agree with you. Basically I think the type enum should be replaced by this forth level of category. However, it would require a huge rewrite of all scripts. Do we want to do it now?

**Comment by plata** [comment]
If we want to do it, we should do it soon (not a good idea to do it after people have there local repositories...).

**Comment by plata** [comment]
I'm not yet sure how the `Functions` tree should look like. E.g. the `Verbs` are currently in parallel to `Engines` but in fact they only work with Wine. Maybe it would make sense to put everything which belongs to Wine into the Wine directory.

**Comment by madoar** [comment]
I think we should go with a change if it's useful and/or makes the code more readable and understandable

**Comment by plata** [comment]
I thought about it again.

Our repository structure has a big issue currently: It's not flexible enough.
As an example, suppose you want to provide ONLY a custom set of apps for Wine. This is not possible without forking the JS files for Wine as well.

Therefore I propose the following: Keep the 3 level namespace but split the Scripts repository. One repository for apps, one for Wine (and everything related e.g. Verbs) and one for utils (e.g. filesystem).
With that approach, the repository structure is a lot clearer and you can plug and play the things you need.

@madoar @qparis I'd like to hear your opinion on this.

**Comment by madoar** [comment]
The idea is good, but I'm not sure how to handle this inside POL 5. 
As far as I understand your suggested approach, we would then need to support 3 different repository types (namely scripts, engines and filesystem). How should the user manage, which of these kinds of repositories he wants/needs?

**Comment by plata** [comment]
There wouldn't be any difference to now. Except that your repository list has more entries.

**Comment by madoar** [comment]
Which means we wouldn't need to add more repository classes? How should POL 5 detect which type of repository it currently looks at?

**Comment by plata** [comment]
The same way as it does not. If you think about it, there is no difference for the software at all. It justs iterates over a bunch of directories. It doesn't matter where those are located.

**Comment by madoar** [comment]
Ah ok, then I think we can go with this approach.

**Comment by plata** [comment]
@qparis you're the only one who could do this.

**Comment by plata** [comment]
another question: why do we have to use a fixed level include and don't use `load()`?

**Comment by madoar** [comment]
Are there any news about this?

**Comment by plata** [comment]
Not really. I still think that the best idea would be to simply split the repository. However, only @qparis can decide about/do this.

**Comment by qparis** [comment]
What name do you propose for the fourth level?

**Comment by plata** [comment]
I see two possibilities:
1. fourth level
    - repository
        - framework
            - engines
            - ...
        - applications
            - games
            - ...
2. Keep three levels and make the scripts in "Functions" first class citizens.
    - engines
        - wine
            - shortcut
            - ...
    - applications
        - games
        - ...

If we choose 1., this structure should also be reflected in the DTOs (i.e. we should separate the scripts in "Functions" from the `ApplicationDTO`). In case 2., we could keep the DTO hierarchy as is (it would probably still make sense to rename `ApplicationDTO`).

**Comment by madoar** [comment]
I think this is currently blocking many of the other features right?
The only issues we could currently work on are graphic related issues, like fixing a panel or something.
Maybe some of these issues make more sense to work on, after this has been completed too.

**Comment by plata** [comment]
We should find an agreement. I'll vote for possibility 2.
