### ISSUE TITLE
AppPanel style is not updated

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#747]
The style of the `WebView` in the `AppPanel` is not updated when you change the theme.

**Comment by madoar** [comment]
I'm not sure how to do this, do you have an idea?

**Comment by plata** [comment]
Not really. Maybe we could bind the `userStyleSheetLocationProperty` of `WebEngine` to the `ThemeManager` somehow (don't know if that would even reload the CSS). However, this issue is not important at all (you will not notice unless you switch themes all the time). Therefore it should not be assigned to "Beta".

**Comment by plata** [comment]
Do you see now why I said that milestones are probably better suited than the project (looking at the amount of manual work you had updating this)?

**Comment by madoar** [comment]
Yes I do -_-
