### ISSUE TITLE
Add a "close" button to the details view

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#759]
Currently it's only possible to close the details view through a category change or a searchterm entry.
In addition to these methods we should also provide a "close" button for the details view, that enables the user to close it and maybe also do some cleanup work, like clearing the selection in the miniature list widget.

A basic close button css class for the default layout can be found in #738.
For more details see #737 and #738.

**Comment by madoar** [comment]
@plata I'm thinking about which container component to use for this. I think we should use either a `StackPane` or a `BorderPane`, what do you think would be best?

**Comment by plata** [comment]
I think `BorderPane`. Maybe like:
![close](https://cloud.githubusercontent.com/assets/3973260/26284027/7260be06-3e32-11e7-85d5-c0b6b369ff63.png)

**Comment by madoar** [comment]
Exactly, the only problem with the `BorderPane` approach is, that it has this ugly empty space above the "title" of the details panel.

**Comment by plata** [comment]
Yes. That's the reason why I'm not sure if we should really have such a button. It's quite ugly and to be honest I don't really see the huge benefit.

The other option would be to collapse it from the left side:
![collapse](https://cloud.githubusercontent.com/assets/3973260/26284071/2d8fc334-3e33-11e7-9169-568216624576.png)

**Comment by madoar** [comment]
How should this behave? When using such a button I would expect that another one is on the right side, that let's me enlarge the screen again afterwards.

**Comment by plata** [comment]
You're right. Doesn't make sense as you could select a different app in the meantime.

**Comment by madoar** [comment]
I think we should go with the `BorderPane` approach, with a slight modification.
Why not define an abstract class that requires a `Optional<String> getViewTitle()` method to be implemented. The `MainWindowView` then takes an object of this abstract class type and adds the optional title next to the "close" button in the "header" bar?

**Comment by plata** [comment]
Or a `DetailsView` which is implemented by `LibraryPanel`, `AppPanel` etc.

**Comment by madoar** [comment]
I guess we mean the same thing, my abstract class would then be called `DetailsView`.
Or do you suggest adding the close button inside the `DetailsView` class?

**Comment by plata** [comment]
Yes that was my idea. However, in the end it doesn't really matter which way we choose.
