### ISSUE TITLE
Maven formatter plugin seems to ignore indention

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#765]
After executing `mvn java-formatter:format`, it seems like the indention is ignored.

**Comment by madoar** [comment]
A reason for this could be the used version of the plugin.
We're currently using version 0.4, but it seems like version 2.0 is the most current one.
But I'm also unsure which version to use, because they seem to target different eclipse versions.
See https://github.com/revelc/formatter-maven-plugin for more details

**Comment by plata** [comment]
Are you sure that this is the same plugin?

**Comment by madoar** [comment]
Not 100%, but because google code is offline for a while now and https://github.com/revelc/formatter-maven-plugin was previously called maven-java-formatter-plugin and located at google code, I'm guessing that it's the same plugin.

**Comment by plata** [comment]
I tried this plugin in plata:formatter but I cannot make it work (don't know enough about maven). I followed the example for [Multimodule Configuration](http://code.revelc.net/formatter-maven-plugin/formatter-maven-plugin/examples.html).

**Comment by madoar** [comment]
What error are you receiving?
In addition it seems like you've forgotten to add a dependency to build-tools:
```
          <dependency>
            <groupId>com.github.hazendaz</groupId>
            <artifactId>build-tools</artifactId>
            <version>1.1.2</version>
          </dependency>
```

**Comment by plata** [comment]
```
Plugin net.revelc.code.formatter:formatter-maven-plugin:2.0.1 or one of its dependencies could not be resolved: Could not transfer artifact org.phoenicis:build-tools:jar:5.0-SNAPSHOT from/to m2e-core (https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST): Cannot access https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST with type p2 using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST with type p2 using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout p2
```
Seems like it tries to upload the `build-tools` module to some website... No idea why.

**Comment by madoar** [comment]
The build-tools dependency inside the plugin tags isn't your module. It should be https://github.com/hazendaz/build-tools

**Comment by plata** [comment]
Then I get
```
Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.0.1:format (default) on project phoenicis-configuration: You must provide a Java or Javascript configuration file.
```

**Comment by madoar** [comment]
The message should mean that the following property is invalid:
```
    /**
     * File or classpath location of an Eclipse code formatter configuration xml
     * file to use in formatting.
     */
    @Parameter(defaultValue = "src/config/eclipse/formatter/java.xml", property = "configfile", required = true)
    private String configFile;
```

**Comment by plata** [comment]
Yes. I don't understand how it should know that the config file is located in `build-tools/src/main/resources/eclipse` based on the `pom.xml` from the example for [Multimodule Configuration](http://code.revelc.net/formatter-maven-plugin/formatter-maven-plugin/examples.html).

**Comment by madoar** [comment]
Your own submodules should be already known to maven, because you've defined them a layer above.
I guess something goes wrong when the plugin is resolving the file path. Do you have any additional debug output from the maven plugin?
I'm asking, because the plugin is using the following method internally:
```java
    /**
     * Read config file and return the config as {@link Map}.
     *
     * @return the options from config file or null if not config file found
     * @throws MojoExecutionException the mojo execution exception
     */
    private Map<String, String> getOptionsFromConfigFile(String newConfigFile) throws MojoExecutionException {

        this.getLog().debug("Using search path at: " + this.basedir.getAbsolutePath());
        this.resourceManager.addSearchPath(FileResourceLoader.ID, this.basedir.getAbsolutePath());

        try (InputStream configInput = this.resourceManager.getResourceAsInputStream(newConfigFile)) {
            return new ConfigReader().read(configInput);
        } catch (ResourceNotFoundException e) {
            getLog().debug("Config file [" + newConfigFile + "] cannot be found", e);
            return null;
        } catch (IOException e) {
            throw new MojoExecutionException("Cannot read config file [" + newConfigFile + "]", e);
        } catch (SAXException e) {
            throw new MojoExecutionException("Cannot parse config file [" + newConfigFile + "]", e);
        } catch (ConfigReadException e) {
            throw new MojoExecutionException(e.getMessage(), e);
        }
    }
```
In case the config file couldn't be found it should print a debug message.
If you want to take a look at the resulting source code line:
https://github.com/revelc/formatter-maven-plugin/blob/master/maven-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java 
line 532

**Comment by plata** [comment]
Even if the file is somewhere in a module? Would you mind trying this yourself (you should be able to checkout my branch)?

**Comment by madoar** [comment]
Ok, I got it working. Try the following:
```xml
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <version>2.0.1</version>
				<executions>
					<execution>
						<goals>
							<goal>format</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<configFile>file://${project.parent.basedir}/build-tools/src/main/resources/eclipse/POL_Formatter_Settings.xml</configFile>
				</configuration>				
            </plugin>
```

The problem was that the plugin couldn't find the configfile `inside` the `pheonicis-configuration` project.
To get more detailed information from maven try: `mvn -X clean compile`. `-X` enables the debug output.

**Comment by plata** [comment]
In this case we can leave the config file where it was before. I just moved it to the module because the example said so.

**Comment by madoar** [comment]
Yes, that would have been my next suggestion ;)
