### ISSUE TITLE
Update maven dependencies

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#768]
Currently we're using some outdated maven dependencies (see #767 for example).
Therefore it would be good to go over each of them and update them to a more current or up to date version.
To see for which dependency a newer version exists we can use `mvn versions:display-dependency-updates`.

**Comment by plata** [comment]
Can we use [Versions Maven Plugin](http://www.mojohaus.org/versions-maven-plugin/) and `use-latest-releases` (see [Maven update dependencies in POM](https://stackoverflow.com/questions/973081/maven-update-dependencies-in-pom))?

**Comment by madoar** [comment]
I think that we could at least try.

**Comment by plata** [comment]
@qparis do we need a special plugin version somewhere?
