### ISSUE TITLE
Wine cannot find the ncurses library (libncurses.so.5)

### ISSUE THREAD

**Issue by ycmjason** [PlayOnLinux/POL-POM-5#772]
This happens when I want to run the game.

```
Wine cannot find the ncurses library (libncurses.so.5).
```

Sorry, it's me again. Any idea how to fix this? I seem to have libncurses.so.6 instead of 5.

Note: I am on archlinux.

**Comment by madoar** [comment]
When exactly do you get this error?
@plata, I think you're more knowledgeable about this.

**Comment by ycmjason** [comment]
I am trying to run league client. :(

**Comment by plata** [comment]
I don't know for arch but for Ubuntu this is a duplicate of #741. I guess you just have to install libncurses 5.

**Comment by plata** [comment]
duplicate of #643
