### ISSUE TITLE
Repositories Settings has small unresizable box

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#774]
Why is it like this? This should automatically expand out to the right at I expand a window and automatically contract as I make it smaller. Like Ubuntu's Software & Updates app, for example.

![screenshot from 2017-05-06 19-49-26](https://cloud.githubusercontent.com/assets/3178485/25775135/15b9a430-3296-11e7-8552-d7cca5fa7717.png)
![screenshot from 2017-05-06 19-55-11](https://cloud.githubusercontent.com/assets/3178485/25775136/1c55a3de-3296-11e7-9f8f-b4786d7e8b01.png)
![screenshot from 2017-05-06 19-53-52](https://cloud.githubusercontent.com/assets/3178485/25775138/23f3a67c-3296-11e7-87b7-62dd1beae3ce.png)
![screenshot from 2017-05-06 19-54-11](https://cloud.githubusercontent.com/assets/3178485/25775139/28f1cf1e-3296-11e7-8888-1aa86d3e4372.png)

**Comment by plata** [comment]
fixed by #775
