### ISSUE TITLE
"Refresh Repositories" button in the settings is missing a border in the default theme

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#777]
![grafik](https://cloud.githubusercontent.com/assets/18488086/25813320/636556c8-3419-11e7-85ea-f38daf46129c.png)

**Comment by plata** [comment]
This is caused by
```CSS
-fx-background-color:transparent;
```
If you remove this from the CSS, the border will be back. However, it will look strange because there's an empty space on the left (where the icon is placed).

**Comment by madoar** [comment]
The problem is that it currently doesn't look like a clickable component.

**Comment by plata** [comment]
![button](https://cloud.githubusercontent.com/assets/3973260/25815435/a4e0f312-3420-11e7-8930-94bef87b7cc2.png)

**Comment by plata** [comment]
I don't think we want that, do we?

**Comment by madoar** [comment]
No, that doesn't look good.
Alternatively we can rethink the idea of using the refresh icon inside the button.
What's important in my eyes is that the user sees that POL 5 is doing something, I'm not sure if a simple disable on the button is enough here, any ideas?

**Comment by plata** [comment]
We could add on overlay (StackPane) over the complete repository settings panel (white, opaque) and show the icon there (maybe even spin it with an animation).

**Comment by madoar** [comment]
Let's go with your `StackPane` approach, I think this will look good and give the user the feeling something is currently happening in POL 5.
