### ISSUE TITLE
Add documentation to the wiki for the css classes appMiniature and miniatureImage

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#781]
During #773 we discovered that we need to adjust/add the documentation in the wiki for the new css classes `appMiniature` and `miniatureImage`, which are responsible for the visualization of the images in the `AppPanel` class and the `MiniatureListWidget`.

**Comment by plata** [comment]
I've updated the wiki. Please check if it is ok now.

In case you want to add/update a picture: I select the part which I want to highlight with a rectangle with border radius 5, invert the selection and fill everything with black at 40% opacity.

**Comment by madoar** [comment]
The wiki article looks good to me. What application do you use to prepare the screenshots?

**Comment by plata** [comment]
GIMP.
