### ISSUE TITLE
Necessary features for Release

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#807]
I think it's time we make a plan what needs to be done that we can do a beta or final release of POL 5. 
A release would give us the benefit that we get a larger number of users that test POL 5 and find bugs and things to improve and add. In addition we would attract more people to write scripts compatible with POL 5.

**Comment by plata** [comment]
In my opinion, we could already announce the current version as "alpha" on playonlinux.com. After that, we should prepare for "beta".

The first things we should handle are issues which would otherwise affect people later on, e.g.:
* #796
* #745
* #696
* #579

Before "beta", we should also consider #557.

**Comment by madoar** [comment]
I would also suggest doing:
- #741 
- #731 
- #759 
- #702 
- #643 
either for the "alpha" or "beta" release.
I think we should add a new a new "project" in the projects page here on github with the following sections (and maybe more?):

- Important bugfixes
- Alpha features
- Beta features
- Other features

As a side note: 
Do we still have a SonarQube? Because the link on github seems to be unavailable?

**Comment by plata** [comment]
SonarQube: see #598

**Comment by plata** [comment]
The issues that you linked should be done for beta. I think we can expect people to build alpha from GitHub (so the .deb issues are not so important). I would like to make sure that we do not have big structural changes once people start using the software (e.g. with #796 you must reinstall your apps/rename your folders). Moreover, I want to introduce the Phoenicis brand right from the beginning to avoid confusion (therefore #579 and #557).
Regarding the project: We didn't really use it after we have introduced it. It was just an extra thing to update. Therefore I would suggest to label the issues.

In any case we need some support from @qparis to get the structural issues out of the way (especially #579 and #557). Then we should also think about how we want to handle those kind of issues in the future. If @mulx and @qparis are not available, Phoenicis as a whole will be in trouble which would be a pity.

**Comment by madoar** [comment]
I've just updated out project page, it would be nice if you can take a look at it @plata.

**Comment by plata** [comment]
Ok. As I said before, I'm not really sure how helpful this is. Maybe milestones would be better.

**Comment by plata** [comment]
Created milestones alpha + beta which shall be used to track the progress of the required issues.
