### ISSUE TITLE
create localization roadmap

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#808]
Create a roadmap for the localization of Phoenicis. This includes:
* this application
* scripts (see PlayOnLinux/Scripts#49)
* website? (see #557)

For the Phoenicis application:
* decide how to do localization with Java(FX) (e.g. this [tutorial](https://docs.oracle.com/javase/tutorial/i18n/index.html), or with [GNU gettext](https://www.gnu.org/software/gettext/manual/html_node/Java.html))
* decide where to store the localization files in a way that people can provide localization files in an easy way
  * [Transifex](https://docs.transifex.com/formats/java-properties) (nice but expensive)
  * [Weblate](https://weblate.org/en/) (free, integrates with git/GitHub)
  * [Pootle](http://pootle.translatehouse.org/)
  * Rosetta (as in #4; often slow and buggy)

**Comment by plata** [comment]
I'm currently looking at [gettext commons](https://github.com/jgettext/gettext-commons) which looks promising. However, I could not quite get it running yet.

**Comment by madoar** [comment]
What problems did you meet?
I would like a solution for this, that can be updates via the web.
This would enable us to update the language files more often that the software itself, which would make sense when we fix some typos or want to add new languages

**Comment by plata** [comment]
With the explanations from the gettext commons wiki, it's quite easy to add the Maven dependencies. Running `mvn gettext:gettext` will then give you a `pot` file with the extracted keys. I don't currently understand how to generate `po` files per language (if that can be done with Maven as well or not etc.) and how the generated classes/properties should be accessed from Java.

**Comment by plata** [comment]
Here are some other tutorials:
<http://blogs.igalia.com/dpino/2009/08/30/setting-up-gettext-commons-for-i18n-java-files/>
<http://blogs.igalia.com/dpino/2009/09/05/using-gettext-commons-from-java-files/>

**Comment by plata** [comment]
Ok. Getting closer:
* use [msginit](https://www.gnu.org/software/gettext/manual/gettext.html#msginit-Invocation) to create a `po` (`msginit -i keys.pot -o de.po`)
* call `mvn gettext:merge`
* call `mvn gettext:dist` (this creates a `Messages_de.properties`)

**Comment by plata** [comment]
see #822

**Comment by plata** [comment]
Translations are working. Translation service to be handled in #898.
