### ISSUE TITLE
Improve the IconsListWidget

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#810]
Currently it seems to me that each `IconsListElement` inside a `IconsListWidget` looks kind squeezed.
Therefore I would suggest to make the `IconsListElement` a little larger and enable the title at the bottom of each `IconsListElement` to contain up to two lines of text. This makes it possible to also show slightly longer titles correctly (and fully).

**Comment by plata** [comment]
Yes. I've also been thinking about two lines for the title already.

**Comment by madoar** [comment]
I think, if we want to make the title take up up to two lines, we'll need to change the dimension of the `IconsListElement` to be a square. 
I'm not sure if this would break the current look of the `IconsListWidget`.
