### ISSUE TITLE
[Feature] Create a shortcut inside a container

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#833]

**Comment by madoar** [comment]
We need a bit more information here I think.
I believe you want to have a button for a selected container inside the `Containers` tab, where the user is able to create a new shortcut that is shown in the `Library` tab? Or are you talking about system shortcuts?

**Comment by qparis** [comment]
That's correct

**Comment by madoar** [comment]
I think this should be done together with #780.
