### ISSUE TITLE
[Unity theme] The text on the orange background should be white color.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#838]
The text on the orange background should be white color.
![zrzut ekranu z 2017-05-28 13-16-28](https://cloud.githubusercontent.com/assets/23406555/26528268/23c151e0-43a8-11e7-88ad-1320aeeb86a7.png)
This is image with the white text edited by me in gimp (:P)
![zrzut ekranu z 2017-05-28 13-16-28editybygimp](https://cloud.githubusercontent.com/assets/23406555/26528326/b4df0428-43a9-11e7-8a52-38793ea8e0d9.png)

**Comment by madoar** [comment]
The unity theme is defined inside `https://github.com/PlayOnLinux/POL-POM-5/tree/master/phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity`. If you want you can add your improvements to the theme directly inside, and submit a pull request afterwards.
This would help us a lot. :)

To test it you simply need to run `mvn test` or `mvn clean package` to trigger the preprocessing of the less files to css files afterwards you can run the application.
