### ISSUE TITLE
[Medium / Difficult] HiDPI Support

### ISSUE THREAD

**Issue by benwaffle** [PlayOnLinux/POL-POM-5#84]
I think you just need to scale everything 2x
![hidpi](https://cloud.githubusercontent.com/assets/1713819/8006006/af8c8422-0b5d-11e5-9644-c0b6340f757f.png)

**Comment by seijikun** [comment]
This [StackOverflow thread](http://stackoverflow.com/questions/26182460/javafx-8-hidpi-support) suggests, that HiDPI on Mac's should just work. For Windows and Linux, using the em unit within the css sets could lead to the desired result. Unfortunately, I don't own any device with HiDPI, so I can't test that.

**Comment by qparis** [comment]
Interesting. It means that we have to scale everything in CSS and stop hardcording size of the widget. I can confirm that retina screens on OSX are fully supported as it. 
This task is high priority.

**Comment by qparis** [comment]
How does it look now?

**Comment by benwaffle** [comment]
still unscaled (i.e. too small)

**Comment by qparis** [comment]
Screenshot?

**Comment by benwaffle** [comment]
![hidpi](https://cloud.githubusercontent.com/assets/1713819/8150634/054a6e8e-12bf-11e5-9fdd-da5cb40924dd.png)

**Comment by qparis** [comment]
What's about wine windows?

**Comment by benwaffle** [comment]
You want me to test a wine app? Programs under wine aren't scaled

**Comment by qparis** [comment]
What about QT programs?

**Comment by benwaffle** [comment]
Looks like GTK2 apps
![qt](https://cloud.githubusercontent.com/assets/1713819/8150663/4f006c58-12c0-11e5-99e0-04542ced1ad1.png)

**Comment by benwaffle** [comment]
With env var
![qt](https://cloud.githubusercontent.com/assets/1713819/8150664/9af9b236-12c0-11e5-8bf1-be908ea7e39d.png)

**Comment by qparis** [comment]
Ok, we need to define a CSS for HDPI devices then.

**Comment by benwaffle** [comment]
say when

**Comment by qparis** [comment]
We have two differents roads:
* JavaFX will support theme. One of them will handle HDPI screens
* We are also going to implement a native GTK UI

A first preview of the GTK UI should be available soon

**Comment by Mannshoch** [comment]
In windows you could scale all apps through a systemwide DPI manipulation.

**Comment by qparis** [comment]
There is a HDPI theme now

**Comment by deevus** [comment]
@qparis How do you configure this theme?

**Comment by qparis** [comment]
Settings, but the CSS of the HDPI theme still needs to be tunned

**Comment by tristan-k** [comment]
Cant find the theme settings in playonlinux.

![screenshot mon jan 30 2017 12 54 14 gmt 0100 cet 505x538](https://cloud.githubusercontent.com/assets/732025/22422179/65c0aa7e-e6eb-11e6-9302-8eb096527926.png)

**Comment by qparis** [comment]
This is POLv4
