### ISSUE TITLE
ObjectMapper does not work in all cases

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#842]
When you show certain apps (e.g. Age of Empires II HD) in the `LibraryPanel`, you get
```
[JavaFX Application Thread] WARN org.phoenicis.javafx.views.mainwindow.library.LibraryPanel - Could not parse shortcut script JSON
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: {"type":"WINE","wineDebug":"-all","winePrefix":"Age of Empires II HD","arguments":["-silent","-applaunch",221380],"workingDirectory":"/home/plata/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam","executable":"/home/plata/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/Steam.exe"}; line: 1, column: 83] (through reference chain: java.util.LinkedHashMap["arguments"])
```

This is a regression because the previous solution worked.

**Comment by madoar** [comment]
How is the json code created?
There is a mismatch between the definition and the Java result type.
The reason is the steam `appId`, which is interpreted as a number in javascript, but java requires a `String`.

**Comment by qparis** [comment]
The reason why this code fails is that because we are not using DTOs

We should always map json contents to DTO to avoid such problems.

Additionally, Jackson can let us specify the type of a json object in a specific field so that objectMapper knows what DTO should be used

**Comment by plata** [comment]
@qparis so you want a DTO for the `script` inside the `ShortcutDTO`? I don't think that's possible because it depends on the engine (e.g. "wineDebug"). If we create a `DTO` for it, we cannot have user defined engines anymore. The previous solution just printed the values for every key in the json and did not try to map anything therefore it did not have a problem.

**Comment by qparis** [comment]
Same for the the current approach except that we should deserialize in a Map<String, Object>
