### ISSUE TITLE
Duplicate miniatures when using multiple repositories

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#848]
When you have two, or more, repositories with the same script miniature, it is shown twice:
![grafik](https://cloud.githubusercontent.com/assets/18488086/26576813/8b1c4f1a-452a-11e7-8e33-ee3a4c5350c6.png)
We should add a function, which checks for duplicates to prevent POL 5 from showing duplicate miniatures.

**Comment by plata** [comment]
Strange. This should have been handled in #398 already.

**Comment by madoar** [comment]
My guess is that the reason for this is our change to `URI` objects.
We need a method that compares the files behind the `URI`s.

**Comment by plata** [comment]
Ah yes. It used to compare the `byte[]`. Can we compare checksums of the files or do we have to read the picture into a `byte[]` just for the comparison?

**Comment by madoar** [comment]
I think a checksum would be enough, do we have a library that can give us one easily.

**Comment by plata** [comment]
Maybe [this](https://stackoverflow.com/questions/304268/getting-a-files-md5-checksum-in-java)?

**Comment by madoar** [comment]
[This](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/digest/DigestUtils.html) would be easier to use I think.

**Comment by plata** [comment]
Can you try it?

**Comment by madoar** [comment]
Yes, I'll do this together with a refactoring of `MergeableRepository`.
What I don't really understand is the condition for when two scripts should be merged?
Is it only when the name of the scripts are equal?
Currently we have no case for when an application in the "Apps" tab contains more than one script and I don't know how to achieve this...

**Comment by plata** [comment]
You can just copy the folder with the script and rename it such that you get e.g. `Steam` and `Online`. I think it's sufficient to merge by name such that two `Online` scripts are merged (of course, `Steam` and `Online` should not be merged).

**Comment by madoar** [comment]
Are you sure the script name is taken from the folder name? The reason for the question is that the `script.json` file contains a `scriptName` attribute.

**Comment by plata** [comment]
I'm not sure where it's coming from. Actually the name in the json is the same as the folder name currently as far as I'm aware.
