### ISSUE TITLE
Prevent deselection of selected list widget

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#853]
Currently it's possible to show the currently selected list widget as "deselected" by clicking on it when it's selected. We should prevent this.
![grafik](https://cloud.githubusercontent.com/assets/18488086/26601657/f957f384-4580-11e7-8f7a-1ab9a793eff0.png)
I would suggest to use the same approach we used to prevent the user from deselecting the currently selected engine/application category.

**Comment by plata** [comment]
I cannot reproduce this.

**Comment by madoar** [comment]
You need to click on the selection button in the left bottom corner a second time, after it has been selected.
After doing this it should look "unselected", like on my screenshot.
