### ISSUE TITLE
ScriptDTO#requiresNoCD seems to be inverted

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#856]
During #847 I discovered, that the value inside `ScriptDTO#requiresNoCD` seems to be inverted.
This means, that when you want to say that a script doesn't require a CD the value needs to be false.
This can be illustrated by my code inside the `ApplicationFilter` class, where "show't" should be "don't":
```java
        /*
         * If "No CD required" is selected show't show games that require a CD
         */
        if (containNoCDApplications.getValue()) {
            result &= application.getScripts().stream().anyMatch(script -> !script.isRequiresNoCD());
        }
```

**Comment by plata** [comment]
I'm not even sure that the meaning of "requires no CD" is understandable. I would prefer "requires disk".

**Comment by qparis** [comment]
It has not the same meaning

**Comment by plata** [comment]
So what's the true meaning then?

**Comment by plata** [comment]
Just checked again in <https://github.com/PlayOnLinux/Scripts/wiki/script.json>. So the meaning is "requires no CD patch/crack". That's absolutely not obvious in the software.

**Comment by qparis** [comment]
Yeah, we should call it _require software modification_ maybe

**Comment by plata** [comment]
@madoar is this issue still valid after this clarification?

**Comment by madoar** [comment]
If we move the renaming work, and maybe the modification of the filter to #860, then I guess we can close this.

**Comment by plata** [comment]
Which modifications should be done for the filter?

**Comment by madoar** [comment]
Oh, you're right the name of the `BooleanProperty` containNoCDApplications confused me, I think we don't need to change the filter.
But we should rename both the field in `ScriptDTO` and the `BooleanProperty` in `ApplicationFilter`

**Comment by plata** [comment]
Ok.
