### ISSUE TITLE
Select branch for GitRepository

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#857]
Currently when adding a `GitRepository` to POL 5, the master branch is cloned.
It would be useful to have the ability to select a branch of a git repository in which the POL 5 application repository is located.
I guess this should be implemented together with #776.

**Comment by madoar** [comment]
I've thought about this a bit. 
I believe we will face two main challenges when we try to do this:

- we will need an interface that allows us to add the branch **in addition** to the repository url. I guess this could be solved best by #776.
- we will need to save the branch information next to the repository url. I'm not sure how to approach this. I don't know of a way to include the branch in the repository url, therefore we would need another way to save it.

**Comment by plata** [comment]
We could add another separator e.g. something like "git+https://github.com/PlayOnLinux/Scripts#master".

**Comment by plata** [comment]
Or like GitHub (`tree` as separator) "git+https://github.com/PlayOnLinux/Scripts/tree/master".

**Comment by madoar** [comment]
I'm not sure if `tree` is a good separator, because this could be a valid part of the path to a git repository.
Can `#` be used inside a typical url to a git repository?

**Comment by plata** [comment]
Just created two branches: `a#b` and `a/tree` so it's probably not a good idea...

**Comment by madoar** [comment]
Is it maybe possible to persist the repositories in json or xml, instead of like we currently do?

**Comment by plata** [comment]
Maybe but that would be a big effort I think.

**Comment by plata** [comment]
Check this out: <https://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name>.

According to this, we could use "git+https://github.com/PlayOnLinux/Scripts:master".

**Comment by madoar** [comment]
`:` is bad too in my eyes, because you can use it to specify a port in your url. 
I'm not sure about the other characters.

**Comment by plata** [comment]
I don't see the problem. If we split on the last `:`, everything should be fine. "git+https://github.com/PlayOnLinux/Scripts:master:8080" will not work anyways.

**Comment by madoar** [comment]
No, but `http://github.com:8080/PlayOnLinux/Scripts would be valid`, if your could reach a server under this url, right?

**Comment by plata** [comment]
It's maybe a valid URL but not a valid entry for our property anymore (would have to be "git+http://github.com:8080/PlayOnLinux/Scripts:master").

**Comment by madoar** [comment]
I think it's real possibility, that such a git url will used. 
It would be quite useful if we find a character that is not found in an encoded git repository url

**Comment by plata** [comment]
I still don't see the problem. Why do you think that the meaning of "git+http://github.com:8080/PlayOnLinux/Scripts:master" might not be clear?

**Comment by madoar** [comment]
Oh, I think we're talking about two kind of problems. Currently I'm thinking about how to parse this parse this kind of URL easily. I would like to use a regex expression that parses the whole entered string, and splits it in all necessary components. I think this would be easier if the split character for the branch would be used at most once in the url

**Comment by plata** [comment]
I would simply:

1. split on `;` to get parts of the list
2. check if it's git
3. split on last `:` to get branch

You cannot use one regex anyways because e.g. the classpath looks different already.

**Comment by madoar** [comment]
I'm not sure this is all in all a good approach.
Let's think a bit more about the topic of supporting git repositories.
Another nice to have feature would be authentication, via password or ssh key.
To support this we would need to add another value to the repository url for persistence. I'm not sure this is feasible...

**Comment by plata** [comment]
In this case, we should really use json.
