### ISSUE TITLE
Decide if the fallback in getMainMiniature is needed

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#859]
See #854 for more details.

**Comment by madoar** [comment]
@plata, @qparis any suggestions about this?

**Comment by qparis** [comment]
I think the default miniature with the logo is a good fallback. I would not like to see screenshot in the main menu, it would not be esthetic

**Comment by plata** [comment]
Agree.

**Comment by plata** [comment]
@madoar are the comments above information to implement a fix for this issue?

**Comment by madoar** [comment]
Yes, the only thing required to fix this issue is to remove the if condition in `getMainMiniature`
