### ISSUE TITLE
Rationalize and decentralize translations

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#879]
Currently, we have two translations systems running concurrently. 
As a consequence, it makes things really hard to understand for an external developer and it prevents repositories to propose translations for the main programs (i.e. category names) 
I suggest to:
- have a unique tr() method that translates a string into many languages.
- use repositories to provide translations. Main program translations will be included in a ClasspathRepository and Script translations will be included in a git or directory or whateverRepository

@plata @madoar

**Comment by madoar** [comment]
So you're basically suggesting to use a javascript i18n solution for everything?

**Comment by qparis** [comment]
On the contrary, I'm suggesting to use a java solution for everything and call it from JS files

**Comment by madoar** [comment]
Hmm, wouldn't this lead to us writing a new library for i18n?

**Comment by madoar** [comment]
I kind of like the idea to use a solution written in javascript that uses a json file as the translation sources.
If we can wrap this javascript solution inside a java interface, then we could use it from java too...

**Comment by qparis** [comment]
It would mean that you would have to instanciate a javascript engine for each string read. In term of performance, I'm pretty sure that it is very bad

**Comment by madoar** [comment]
Not sure I agree with this.
Doesn't the java scripting api have a method to convert a javascript object to a java interface, which makes the access to the object easier? 
I don't know how this is implemented, but I don't think that it has been done too performance hungry.

**Comment by qparis** [comment]
There are a lot of strings everywhere in POL so it will surely have an impact on memory footprint at least. I was thinking about something like this: (Java = blue, Javascript = Green) 
![sans titre](https://user-images.githubusercontent.com/373645/26852753-9dd1449a-4b0f-11e7-9e03-90edc50f6945.png)

**Comment by qparis** [comment]
The advantage of using .po and .pot files, is that the translations are compatible with platforms like Rosetta

**Comment by madoar** [comment]
I guess the problem here is, that for our current solution the translation files are used to generate class files in the compile phase (if I understood @plata correctly). This would make our current solution unusable.
We would need a solution that can search for translation files at runtime, because of our script repositories, which can be plugged in at runtime.
I'm not sure such a solution exists in java.

**Comment by qparis** [comment]
We certainly can: 

<img width="605" alt="capture d ecran 2017-06-06 a 23 30 48" src="https://user-images.githubusercontent.com/373645/26852908-3155d316-4b10-11e7-8bc4-65b3123c1442.png">
gives 
<img width="882" alt="capture d ecran 2017-06-06 a 23 31 04" src="https://user-images.githubusercontent.com/373645/26852919-3ba5e586-4b10-11e7-8230-c86b42f03c6d.png">

**Comment by madoar** [comment]
Another problem are the .po and .pot files themselves in my eyes. For java projects there are tools to generate them from source code.
For scripts this is impossible, because they are written in javascript.
From their format, it seems to be a pain to create them....

**Comment by qparis** [comment]
@madoar Tools can generate .pot files from basically any languages. I'm using them with Python and PHP for POLv4, I'm pretty confident that the same exist in JS

**Comment by madoar** [comment]
Ok, didn't know that .pot files were standard. I haven't used i18n before in my projects.
But still I feel that this is not a good solution, especially when json objects look kind of more compact and better readable....
But I agree, we should find a solution that needs to be able to be able to load new translations at runtime and work for both java and javascript

**Comment by qparis** [comment]
Hardly any translation platform will use .pot file in fact. They are compilable, it is truely a standard.
But if you look at my previous screenshot, you'ok see that we can imagine a component that will accept two different kind of files

**Comment by madoar** [comment]
Yes but this would mean, that we need to write a new solution to find the translations for a given key. This seems to me like the longest, most complex and the core part of an i18n library.

**Comment by qparis** [comment]
I'm pretty sure that there is a way to parse a .po or .mo file in a HashMap

**Comment by plata** [comment]
@qparis you should keep in mind that proper l10n requires more than just a lookup in a HashMap. There's plural forms, numbering and what not.
I agree that it would be pretty cool if we could read .po's at runtime and pass them as input to gettext-commons.

**Comment by qparis** [comment]
In POLv4, we have never used plurals and other stuff

**Comment by plata** [comment]
Maybe. But that doesn't mean that we will never need it.

**Comment by qparis** [comment]
In any case, the point I'm describing is really crucial, so we have to find a solution

**Comment by plata** [comment]
I think we can do the same as gettext-commons: call `msgfmt` at runtime and read the generated file (see [here](http://xnap-commons.sourceforge.net/gettext-commons/tutorial.html))

**Comment by plata** [comment]
However, this doesn't help for `json`: We need a `tr()` around the String so the `.pot` is generated. I don't think it's possible to call a function in `json`, is it?

**Comment by qparis** [comment]
I think it is acceptable to have very few items not generated in the pot file

**Comment by plata** [comment]
So we use the solution in #876, PlayOnLinux/Scripts#257 and PlayOnLinux/Scripts#256 for the json files? Or do you want to add those strings to the pot manually (if that's even possible)?

**Comment by plata** [comment]
The only think I found is not to use `json` but JS files with objects [1](https://stackoverflow.com/questions/39586651/json-and-translation) or `intltool` to extract all strings [2](https://stackoverflow.com/questions/24990707/how-do-i-get-strings-from-a-json-file). For 2 I don't understand how this should work because double quotes are required for `json`.
We could write a small preprocessor script which parses the `json` files and extracts the strings which shall be translated (we know exactly which parts of the `json` shall be translated).

**Comment by qparis** [comment]
I don't understand your last comment

**Comment by plata** [comment]
How do we translate the json? In my opinion we have 2 possibilities:

1. Create a json per language (e.g. application_de.json)
2. Put the Strings from the json into the .pot. If we want to do this, we need a script which extracts the Strings from the json because xgettext cannot do that directly.

**Comment by qparis** [comment]
Json is a subset of JavaScript so I don't see why gettext would no read it... is it because you would need to include tr inside the json?

Anyway, why do you want these files to be scanned automatically? It is acceptable if every strings except the json on are detected in a first time

**Comment by qparis** [comment]
Also tr could be a little smarter:
* If the argument is a string, translate it,
* if it is an object or a dictionary, returns argument[language]

**Comment by plata** [comment]
Yes, because we would need tr in the json. I think we should have a concept which covers all relevant cases before implementing something.

**Comment by plata** [comment]
Just had a look at it. Does anyone know how we can merge all the properties files into one ResourceBundle?

**Comment by plata** [comment]
see #881

**Comment by plata** [comment]
@qparis I think we can close this?
