### ISSUE TITLE
Update Wiki with new repositories.json file

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#883]
After we've moved the repository list to a new `repositories.json` file we need to document this in the wiki.
I suggest that we do this after the new git repository field `branch` has been added.

**Comment by madoar** [comment]
What type or repository do you want to add?

**Comment by plata** [comment]
local

**Comment by madoar** [comment]
My `repositories.json` file looks like this:

```json
[{"type":"git","gitRepositoryUri":"https://github.com/PlayOnLinux/Scripts"},{"type":"git","gitRepositoryUri":"https://github.com/PlayOnLinux/Oldwares"},{"packagePath":"/org/phoenicis/repository","type":"classpath"},{"repositoryLocation":"/home/user/path/Play on Linux/Scripts","type":"local"}]
```

**Comment by plata** [comment]
Can you just replace the current wiki page with this information? Should be enough to configure it already.

**Comment by madoar** [comment]
I'll do this soon (today or tomorrow).

**Comment by plata** [comment]
Thanks.

**Comment by madoar** [comment]
I've just updated the wiki article https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository.
Can you please take a look at it? 
If it fulfills the requirements we can close this issue.

**Comment by plata** [comment]
> a json array or repository objects

or "of"?

**Comment by plata** [comment]
* use Phoenicis instead of POL5
* address the reader: "please add" instead of "the user needs to add"
* "An examples for a local repository" => "An example for a local repository"
* "as the URI to the the repository" is a bit strange because you refer to the json content

**Comment by madoar** [comment]
Ok, I've added your suggestions to the Wiki.
Is it ok now?

**Comment by plata** [comment]
If you fix "An examples for a local repository" => "An example for a local repository", then yes.

**Comment by madoar** [comment]
Fixed
