### ISSUE TITLE
wine cannot load libudev.so.0

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#889]
At least on Ubuntu 16.04 only libudev1 is available. Can we do anything about this in Phoenicis?

It can be solved via:
```bash
sudo ln -sf /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
```

**Comment by madoar** [comment]
For what is this library needed?
I'm not sure we can do something about this.
For one, we would need `sudo` rights to execute your given command. In addition this seems to depend on the type of linux flavor you use, right?
What I would suggest is showing the user a message if an important library is missing.

**Comment by plata** [comment]
I don't know why it is needed.
Maybe we could do something in the generation of the `.deb` or provide `libudev` in the `lib` folder of Wine.

**Comment by plata** [comment]
Like @madoar pointed out, this depends on the the OS (and even the particular Linux distribution). Therefore we cannot handle it in a common way.
I have added a [Troubleshooting](https://github.com/PlayOnLinux/POL-POM-5/wiki/Troubleshooting) page to the wiki in case someone is experiencing this issue.
