### ISSUE TITLE
A half-automatic wizard for easier creation installation of scripts?

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#890]
What do you think about adding possibility is a half-automatic wizard for easier creation installation of scripts? The wizard asks questions about the app, for example website link and save the wine version and other parameters of current installation.

**Comment by qparis** [comment]
This has been done in POLv4 before and in general, it leads to poorly tested scripts

**Comment by madoar** [comment]
I believe a better idea would be to provide a validate function, that helps script developers to see if their scripts are syntactically correct.
This is especially important if functions are used inside scripts that are implemented in java.
What do you think?

**Comment by plata** [comment]
I don't really see the point. You can just run the script and you will see if it works or not. Also, the scripts which could be created by such an half-automatic wizard are so simple that no-one should have a problem writing them in JS directly (even if you have absolutely no clue about programming).

**Comment by madoar** [comment]
Such a validation script would help to prevent us from doing changes to POL 5, that are not compatible with a few scripts. 
This is currently a problem, that we do some changes and discover sometimes only a few days afterwards, that scripts don't work anymore.

**Comment by plata** [comment]
That's true. But shouldn't this be done the other way around? I.e. not test a script if it's correct but rather test the software if it does not break the scripts?

**Comment by plata** [comment]
I think from the discussion in this issue, it is clear that this will not be supported.
