### ISSUE TITLE
How to help translate PlayOnLinux5? [Could you give me some counsel]

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#891]
I can translate PlayOnLinux from english to polish but i don't have idea how do it.
Could you give me some instructions or counsel?
I and other users need handbook.

**Comment by plata** [comment]
I will provide a description in the wiki. I think we can start the translation of the software already. For the translation of the scripts, I'm waiting for @qparis approval of  #884 and PlayOnLinux/Scripts#259.

**Comment by plata** [comment]
Here's a quick description: https://github.com/PlayOnLinux/POL-POM-5/wiki/Translation

Please tell me if it's understandable or I should change something.

**Comment by pyroxar** [comment]
Ok thanks
