### ISSUE TITLE
While run playonlinux not saw logo.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#900]
While run playonlinux not show logo.
When I change tab to other, logo is display normal.
it happens always when I run playonlinux.
![zrzut ekranu z 2017-06-17 20-56-20](https://user-images.githubusercontent.com/23406555/27255551-147d71e8-53a0-11e7-829f-611cbc81ed70.png)
![zrzut ekranu z 2017-06-17 20-56-28](https://user-images.githubusercontent.com/23406555/27255553-1abaee32-53a0-11e7-90ed-bbe4aef133ab.png)

**Comment by plata** [comment]
Can you provide the log output?

**Comment by pyroxar** [comment]
Ok.
I don't even know where to find it.

**Comment by plata** [comment]
How do you run it? You should see the log in your console or in your IDE.

**Comment by pyroxar** [comment]
I thought it was about 'special' log too.

This time, playonlinux logo shows after a while.
[log.txt](https://github.com/PlayOnLinux/POL-POM-5/files/1089785/log.txt)

**Comment by madoar** [comment]
@plata I think this is related to the problem we have when you change your scaling in the settings and you need to hover over the logo to make it change.

**Comment by plata** [comment]
@pyroxar can you approve that the logo shows up as soon as you hover it? Otherwise I see two possibilities:
1. It's somehow related to fetching the repository. To check this, you could use only a local repository.
2. #851

**Comment by pyroxar** [comment]
Ok. When I run POL5, logo shows after a little while.
I delete remote repositories. Logo shows immediately.

**Comment by plata** [comment]
Mh. So the logo is loaded only after the repository is fetched. @madoar @qparis any ideas why that happens?

**Comment by madoar** [comment]
I have no idea.

**Comment by madoar** [comment]
Maybe we should think about how we want the startup process of POL 5 to be, because currently we seem to have some issues with it.
For example see also #851.
