### ISSUE TITLE
Prevent scripts from directly accessing Java classes

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#911]
Advantage: 
* Security, a script will no longer be able to damage filesystems
* Portability, one can rewrite a compatible client with existing scripts

**Comment by madoar** [comment]
How do you want to provide the needed functionality, which is implemented in java code, to the scripts?

**Comment by qparis** [comment]
Bean()

**Comment by madoar** [comment]
But then you allow some kind of access to the Java classes, right?
What prevents the script developer then to access other classes?

**Comment by qparis** [comment]
We could easily add a security mechanism, like a custom @Safe annotation and Bean() could check that this annotation exists

**Comment by plata** [comment]
How about: <https://stackoverflow.com/questions/24466203/how-to-remove-java-apis-from-nashorn-engine>?

**Comment by qparis** [comment]
This is complementary

**Comment by madoar** [comment]
I think this might be a nice idea, the question is how to we do this with annotations?
I know of two ways to tell nashorn to ignore classes, the first are command line arguments (see the link from @plata for an example) and a `.policy` file. 
I'm not sure if there is a way to do this at runtime?

**Comment by plata** [comment]
Do we even need the annotation if we make only a certain API available in JS as in the link I posted?

**Comment by madoar** [comment]
I think we will need to have some java classes available to be used in javascript by the scripts.
For these we will need a policy that tells nashorn which classes can and can't be used from inside the scripts.

**Comment by qparis** [comment]
@madoar  Exactly. It is possible (I've done it before with Nashorn). 
The idea is :
 * Bean() and SetupWizard() are allowed to be called because they are injected from java and not the contrary
 * Bean() always checks that the bean the script is trying to instanciate is annotated with @Safe

**Comment by qparis** [comment]
final ScriptEngine scriptEngine = scriptEngineFactory.getScriptEngine(ClassFilter classFilter);

class CustomClassFilter implements ClassFilter {
    @Override
    public boolean exposeToScripts(String fullClassName) {
        return boolean 
    }
}

**Comment by madoar** [comment]
This sounds interesting.
So you would use reflection inside `exposeToScripts` to check if the given class can be exposed?

**Comment by qparis** [comment]
Yes

**Comment by madoar** [comment]
Do you think we'll need to change anything inside our existing scripts when we do this, or would it be enough to provide such a `ClassFilter`?

**Comment by qparis** [comment]
We will need to change some stuff in the wine classes

**Comment by qparis** [comment]
Also, we could introduce the concept of Safe repository

**Comment by madoar** [comment]
What do you mean with "safe repository"?

**Comment by qparis** [comment]
A repository that can execute any script (ClassPath internal repositories, ...)

**Comment by madoar** [comment]
This sounds really interesting.
Do you want to do a PR for this?
I must confess I have no prior knowledge about nashorn so it would be quite nice if you could do this ;)
Afterwards we can discuss about the advantages and disadvantages.

**Comment by plata** [comment]
@qparis can we close this?

**Comment by madoar** [comment]
@qparis Do you want to give the "safe repository" idea a go, or do you think this issue can be closed?

**Comment by madoar** [comment]
Oh I just saw that your previous PR already contained an initial approach for the "safe repositories", so I think we can close this?
