### ISSUE TITLE
Add overview/landscape of the used maven modules in the Wiki

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#927]
Currently we have no explanation page in the Wiki, which tells a new developer which maven module contains what functionality.
We should add such a page.

**Comment by plata** [comment]
Can't we do that in JavaDoc?

**Comment by madoar** [comment]
My idea was to add table to the Wiki, which contains information like:

Maven Module | Documentation
------------------- | -------------------
pheonicis-javafx | Contains the javafx gui application for Phoenicis
... | ...

**Comment by plata** [comment]
Ok. Yes, on this level we can do it manually.

**Comment by plata** [comment]
see [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Modules).
