### ISSUE TITLE
Window of PlayonLinux should be slightly wider.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#932]
Actually in default display mode in tabs like Library, App, Containers or Engines fit only three columns. It is ugly. I think that it is necessary corrections.
![zrzut ekranu z 2017-06-28 11-57-08](https://user-images.githubusercontent.com/23406555/27631704-a315ed84-5bf9-11e7-85f0-6c8c5154226c.png)
![zrzut ekranu z 2017-06-28 11-57-42](https://user-images.githubusercontent.com/23406555/27631707-a7c01198-5bf9-11e7-9e27-e8521805c979.png)

**Comment by madoar** [comment]
This is a question of the scaling you've set.
To make this fit better I think it's enough to change the default scaling to a lower value.
