### ISSUE TITLE
Wine tool tabs are displayed incorrectly.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#933]
![zrzut ekranu z 2017-06-28 11-58-28](https://user-images.githubusercontent.com/23406555/27631993-ac212712-5bfa-11e7-88d6-486066932987.png)

**Comment by madoar** [comment]
Yes, the whole container details view currently has a horrible layout, which needs improving or a rewrite.
The problem here is, that we want to move a lot of features currently written in java to the script repository, more detailed to the wine javascript class which (should/will) implement a java interface.
For more information on the issue take a look at #620.

**Comment by plata** [comment]
@mador I don't think the generic engines are related to this issue. The JS should only provide the content, not the view. This issue should be fixed by using a floating layout in a scrollpane (not fixed grid) like we do for the apps/engines etc. already.

**Comment by madoar** [comment]
My point is, that I would only touch the layout of the container tab, when we decide to do #620.
The reason for this is, that #620 will enable us to query a list of settings objects, which can be added via a for loop to the layout. This is a big change to the current manual layout, which would require a second large change if we did it later on.

**Comment by plata** [comment]
I don't think so. We will just use a loop instead of a fixed set of objects. Moreover, #620 will take some time so we should fix this issue before we do #620.

**Comment by madoar** [comment]
If you we decide to fix this before #620, then I think we should do it in a very flexible way that works with an arbitrary number of elements to be shown in the layout.

**Comment by plata** [comment]
Exactly. That's why I said, it should behave like the apps/engines.
