### ISSUE TITLE
Menu have different sizes in different tabs.

### ISSUE THREAD

**Issue by pyroxar** [PlayOnLinux/POL-POM-5#934]
This difference in menu size is only in settings tab. In other tabs menu size is the same.
![zrzut ekranu z 2017-06-28 11-59-25](https://user-images.githubusercontent.com/23406555/27632138-21e6dc30-5bfb-11e7-990d-9f51db625c32.png)
![zrzut ekranu z 2017-06-28 11-59-33](https://user-images.githubusercontent.com/23406555/27632145-27db60fc-5bfb-11e7-8883-599a8bc4d49a.png)

**Comment by plata** [comment]
Are you talking about the left sidebar? If so, that's on purpose because the sidebar should use as much space as it needs. If it would always use the same width, we would loose space to display content.

**Comment by madoar** [comment]
Here I must agree @pyroxar, normally you would expect all sidebars to have the same size.
The question here is: can we achieve this somehow?

**Comment by plata** [comment]
If we still want the texts not to be cropped and a sidebar which is not fixed to a width which is way too large, I don't see a reasonable way to do this.

**Comment by plata** [comment]
After the discussions in several other issues and pull requests, I'm pretty convinced that the sidebar belongs to every tab. As a consequence, we have multiple sidebar objects. As I said above already, I cannot think of any reasonable way to assign them the same width. For example, this would require to load and update all the tabs all the time even if they are not displayed.

Unless anyone knows a nice solution, I would therefore like to close this issue as "won't fix".

**Comment by madoar** [comment]
I'm also not sure how to best approach this issue.
On the one hand I must agree @pyroxar that it's quite visible if you switch between the different tabs often.
On the other hand I agree with @plata that a uniform sidebar is hard to implement and doesn't fit in our current concept.

**Comment by plata** [comment]
If we merge #948, it will not be that visible anymore because you loose the reference to the logo.

As we cannot find a proper solution, I close this.
