### ISSUE TITLE
Download too slow in china

### ISSUE THREAD

**Issue by michaeldyl520** [PlayOnLinux/POL-POM-5#942]
How can i do?I can down some wine,it`s too slow.

**Comment by plata** [comment]
What exactly is the problem? If you have issues with the repositories, you can download them once and then use local repositories (see [wiki](https://github.com/PlayOnLinux/POL-POM-5/wiki/Repository)). If you cannot download Wine at all, I don't currently see a possibility how this could be fixed (unless you can get Wine from somewhere else).

**Comment by plata** [comment]
Closed as we cannot do anything about the Internet connection. How to use local repositories to download the files only once, has been described above.
