### ISSUE TITLE
Problem with author tag

### ISSUE THREAD

**Issue by ivannarvaez17** [PlayOnLinux/POL-POM-5#943]
Hi, when I tried compiling the source code I kept getting this error:

Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.122 sec <<< FAILURE!
fetchInstallableApplications_Graphics_Photofiltre_scriptContent(org.phoenicis.repository.repositoryTypes.ClasspathRepositoryTest)  Time elapsed: 0.026 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...  .author("Quentin P[?]RIS")
    .url("http...> but was:<...  .author("Quentin P[??]RIS")

I think it might be related to an extra space before ^b, inside this file: /opt/POL-POM-5/phoenicis-repository/target/test-classes/org/phoenicis/repository/repositoryTest/Graphics/Photofiltre/Online/script.js

To complete the compilation process, I had to remove the contents of the  fetchInstallableApplications_Graphics_Photofiltre_scriptContent() function inside: /opt/POL-POM-5/phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/ClasspathRepositoryTest.java

**Comment by plata** [comment]
Does it work if you replace `Quentin PÂRIS` in `phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTest/Graphics/Photofiltre/Online/script.js` by something without special characters (e.g. `Quentin PARIS`)?

**Comment by ivannarvaez17** [comment]
Changing it to PARIS, the error changes to: 

org.junit.ComparisonFailure: expected:<...  .author("Quentin P[?]RIS")
    .url("http...> but was:<...  .author("Quentin P[A]RIS")

Now, if you just remove the space before the ^b then it says:

org.junit.ComparisonFailure: expected:<...  .author("Quentin P[?]RIS")
    .url("http...> but was:<...  .author("Quentin P[?]RIS")

which to me must be mean that: phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java, which is the file that apparently generates script.js, must be adding some funky character in addition to the space, and that's what's causing the assertion to fail.

**Comment by plata** [comment]
It fails because `fetchInstallableApplications_Graphics_Photofiltre_scriptContent` expects `Quentin PÂRIS` but you have `Quentin PARIS`. When you change that line (`.author("Quentin PÂRIS")` in the test as well, it should work. To me, this shows that you have some encoding issue on your machine (that's also why you get `?` instead of `Â`).

@madoar @qparis any ideas what could cause this issue (and why we don't have it)?

**Comment by ivannarvaez17** [comment]
I'm on Arch Linux, at least one other person on the arch user repositories has had the same problem: https://aur.archlinux.org/packages/playonlinux5-git/

**Comment by plata** [comment]
Ok. Maybe the guys at Arch have a better idea about what's going on with the encoding. To be honest, I don't see what we could do about this.

**Comment by madoar** [comment]
This is really strange, I've just checked, both files have a `UTF-8` encoding.
Maybe the script loading method interprets the script as having another encoding?
@ivannarvaez17 Can you tell us your system encoding?

**Comment by ivannarvaez17** [comment]
You were right @plata it actually was an encoding issue on my machine, as per @madoar's suggestion I checked the system encoding of my machine and noticed some of the locale environment variables weren't set, which I fixed following the answer provided in this link: https://stackoverflow.com/questions/28247427/strange-locale-issue-on-arch

**Comment by plata** [comment]
That's good.
