### ISSUE TITLE
missing tooltip to show script source

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#953]
The tooltip which should be shown when the `viewScriptSource` checkbox in the settings has been enabled isn't shown currently.

**Comment by plata** [comment]
@madoar do you still have this problem? It works for me.

**Comment by madoar** [comment]
Yes, I've just checked, I don't see a tooltip when hovering over a script label (e.g. Audiosurf -> "Steam").
Can you maybe post a screenshot how the tooltip looks like, maybe I'm just missing it...

**Comment by plata** [comment]
![tooltip](https://user-images.githubusercontent.com/3973260/28246218-3010cc26-6a15-11e7-9a22-c9750240ed76.png)

**Comment by madoar** [comment]
It seems I've found the problem.
The time until the tooltip opens is kind of long, but it's working.
