### ISSUE TITLE
org.phoenicis.scripts.interpreter.ScriptException: Script not found: [Functions, Engines, Wine]

### ISSUE THREAD

**Issue by aaronfranke** [PlayOnLinux/POL-POM-5#956]
https://pastebin.com/yEw6cJi8

This error comes up when trying to install any version of Wine in the "Engines" tab. Four error dialogs show up and this text is outputted to the terminal log.

Also, once this happens, the window becomes un-resizable, it is stuck at a fixed size.

My system: Xubuntu 16.04 LTS 64-bit, openjdk version "1.8.0_131" from the Ubuntu repos, PoL built using `mvn clean package` after downloading the repository and installing dependencies.

**Comment by plata** [comment]
Should be fixed in the linked PR.
