### ISSUE TITLE
wine cannot load libmpg123.so.0

### ISSUE THREAD

**Issue by ImperatorS79** [PlayOnLinux/POL-POM-5#968]
Europa Universalis 2 is working flawlessly on wine 2.0.2 with POL4

However, with POL5, no music (mp3 files)

NB : libmpg is installed on my PC

**Comment by plata** [comment]
Could this be the same like #643 (i.e. .Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib/ is not in the ld path)?

**Comment by ImperatorS79** [comment]
Since libmpg123.so.0 is inside this directory, there is definitively a problem, but I don't know what is the ld path (something about the .so it seems).

**Comment by plata** [comment]
The `LD_LIBRARY_PATH` specifies in which folders .so files can be found. For more details, check this [wikipedia](https://en.wikipedia.org/wiki/Dynamic_linker).
The Wine JS script queries `PropertyReader` to set it in `Wine.prototype.run`. I assume that the path to the lib folder of the Wine installation has to be added there as well. You could try the following code snippet to check if this is really the case:
```Javascript
this._ldPath = this._ldPath + ":/home/<user>/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib/"
if (this._ldPath) {
    environment.put("LD_LIBRARY_PATH", this._ldPath);
}
```

**Comment by ImperatorS79** [comment]
Where do I have to paste these snippet ? In "Engines/Wine/Engine/Object/Script.js" ?

**Comment by plata** [comment]
Yes, in `Wine.prototype.run`.

**Comment by ImperatorS79** [comment]
Ok, I did it, but wine still complains about the missing .so.

**Comment by plata** [comment]
Do you use 32bit or 64bit? (there are two lib folders)

**Comment by ImperatorS79** [comment]
I use 32bit wine, on my 64bit system

**Comment by plata** [comment]
Then the path should be ok. Does it work if you run Wine manually from the command line?

**Comment by ImperatorS79** [comment]
I don't really know how to do that since PlayOnLinux console doesn't work. I tried something like 

`WINEARCH=win32 WINEPREFIX=~/.Phoenicis/wineprefix/Europa\ Universalis\ II/ LD_LIBRARY_PATH=~/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib/  ~/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/bin/wine ~/.Phoenicis/wineprefix/Europa\ Universalis\ II/drive_c/Program\ Files/Paradox\ Entertainment/Europa\ Universalis\ 2/eu2.exe`

But it crashes

**Comment by plata** [comment]
That's good. In this case, we should extend the script in this way. We have to consider 32/64bit. Moreover, we should think about the priority. It might make sense to set the path the other way around, like
```Javascript
this._ldPath = "/home/<user>/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib/:" + this._ldPath
```
This would ensure that the .so's belonging to the Wine installation are considered before the system ones.

**Comment by plata** [comment]
The Wine path `/home/<user>/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2` can be determined by
```Javascript
this._fetchLocalDirectory()
```
The architecture is stored in `this._architecture`.

So the code should be something like (untested)
```Javascript
if (this._architecture == "amd64")
{
    this._ldPath = this._fetchLocalDirectory() + "/lib64/:" + this._ldPath
} else
{
    this._ldPath = this._fetchLocalDirectory() + "/lib/:" + this._ldPath
}
environment.put("LD_LIBRARY_PATH", this._ldPath);
```

Would be great if you could test this and provide a pull request if it works.
